In [2]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
from config import db_password

In [3]:
df=pd.read_csv('../../all_records.csv')

In [4]:
df.head()

,Unnamed: 0,Animal ID,Name_intake,DateTime_intake,MonthYear_intake,Found_Location,Intake_Type,IntakeCondition,Animal_Type_intake,Sex,...,beagle,terrier,boxer,poodle,rottweiler,dachshund,chihuahua,pit bull,DateTime_length,Days_length
0,0,A730601,NaN,2016-07-07 12:11:00,07/07/2016 12:11:00 PM,1109 Shady Ln in Austin (TX),Stray,Normal,Cat,Intact Male,...,0,0,0,0,0,0,0,0,0 days 20:49:00.000000000,0-7 days
1,1,A683644,*Zoey,2014-07-13 11:02:00,07/13/2014 11:02:00 AM,Austin (TX),Owner Surrender,Nursing,Dog,Intact Female,...,0,0,0,0,0,0,0,0,115 days 23:04:00.000000000,12 weeks - 6 months
2,2,A676515,Rico,2014-04-11 08:45:00,04/11/2014 08:45:00 AM,615 E. Wonsley in Austin (TX),Stray,Normal,Dog,Intact Male,...,0,0,0,0,0,0,0,1,3 days 09:53:00.000000000,0-7 days
3,3,A742953,NaN,2017-01-31 13:30:00,01/31/2017 01:30:00 PM,S Hwy 183 And Thompson Lane in Austin (TX),Stray,Normal,Dog,Intact Male,...,0,0,0,0,0,0,0,0,4 days 00:47:00.000000000,0-7 days
4,4,A679549,*Gilbert,2014-05-22 15:43:00,05/22/2014 03:43:00 PM,124 W Anderson in Austin (TX),Stray,Normal,Cat,Intact Male,...,0,0,0,0,0,0,0,0,24 days 22:11:00.000000000,3-6 weeks

In [4]:
# Check columns
df.columns

Index(['Unnamed: 0', 'Animal ID', 'Name_intake', 'DateTime_intake',
       'MonthYear_intake', 'Found_Location', 'Intake_Type', 'IntakeCondition',
       'Animal_Type_intake', 'Sex', 'Age', 'Breed_intake', 'Color_intake',
       'Name_outcome', 'DateTime_outcome', 'MonthYear_outcome', 'Outcome_Type',
       'Outcome_Subtype', 'Sex_upon_Outcome', 'Age_upon_Outcome',
       'gender_intake', 'gender_outcome', 'fixed_intake', 'fixed_outcome',
       'fixed_changed', 'Age_Bucket', 'retriever', 'shepherd', 'beagle',
       'terrier', 'boxer', 'poodle', 'rottweiler', 'dachshund', 'chihuahua',
       'pit bull', 'DateTime_length', 'Days_length'],
      dtype='object')

In [5]:
# Check null values
df.isnull().sum()

Unnamed: 0                0
Animal ID                 0
Name_intake           19484
DateTime_intake           0
MonthYear_intake          0
Found_Location            0
Intake_Type               0
IntakeCondition           0
Animal_Type_intake        0
Sex                       1
Age                       0
Breed_intake              0
Color_intake              0
Name_outcome          19484
DateTime_outcome          0
MonthYear_outcome         0
Outcome_Type              7
Outcome_Subtype       45254
Sex_upon_Outcome          4
Age_upon_Outcome         21
gender_intake          5608
gender_outcome         5611
fixed_intake              1
fixed_outcome             4
fixed_changed             0
Age_Bucket                0
retriever                 0
shepherd                  0
beagle                    0
terrier                   0
boxer                     0
poodle                    0
rottweiler                0
dachshund                 0
chihuahua                 0
pit bull                  0
DateTime_length           0
Days_length            7400
dtype: int64

In [6]:
# Drop unnecessary columns
# Drop Name_intake since there is a Intake_type column
# Drop all single breed type column since we need to do our own encoding for breed_intake
df=df.drop(columns=['Unnamed: 0','Name_outcome','MonthYear_intake','MonthYear_outcome',
                    'gender_intake','gender_outcome','fixed_intake','fixed_outcome','Days_length','Outcome_Subtype',
                   'retriever','shepherd','beagle','terrier','boxer','poodle','rottweiler','dachshund','chihuahua',
                   'pit bull','Age','Age_upon_Outcome'])
df.head()

,Animal ID,Name_intake,DateTime_intake,Found_Location,Intake_Type,IntakeCondition,Animal_Type_intake,Sex,Breed_intake,Color_intake,DateTime_outcome,Outcome_Type,Sex_upon_Outcome,fixed_changed,Age_Bucket,DateTime_length
0,A730601,NaN,2016-07-07 12:11:00,1109 Shady Ln in Austin (TX),Stray,Normal,Cat,Intact Male,Domestic Shorthair Mix,Blue Tabby,2016-07-08 09:00:00,Transfer,Neutered Male,1,7-12 months,0 days 20:49:00.000000000
1,A683644,*Zoey,2014-07-13 11:02:00,Austin (TX),Owner Surrender,Nursing,Dog,Intact Female,Border Collie Mix,Brown/White,2014-11-06 10:06:00,Adoption,Spayed Female,1,1-6 weeks,115 days 23:04:00.000000000
2,A676515,Rico,2014-04-11 08:45:00,615 E. Wonsley in Austin (TX),Stray,Normal,Dog,Intact Male,Pit Bull Mix,White/Brown,2014-04-14 18:38:00,Return to Owner,Neutered Male,1,1-6 months,3 days 09:53:00.000000000
3,A742953,NaN,2017-01-31 13:30:00,S Hwy 183 And Thompson Lane in Austin (TX),Stray,Normal,Dog,Intact Male,Saluki,Sable/Cream,2017-02-04 14:17:00,Transfer,Intact Male,0,1-3 years,4 days 00:47:00.000000000
4,A679549,*Gilbert,2014-05-22 15:43:00,124 W Anderson in Austin (TX),Stray,Normal,Cat,Intact Male,Domestic Shorthair Mix,Black/White,2014-06-16 13:54:00,Transfer,Neutered Male,1,1-6 months,24 days 22:11:00.000000000

# Name_intake_column

In [7]:
# Change Name_Intake to Yes or No
df.Name_intake = df.Name_intake.apply(lambda x: 'No' if pd.isnull(x) else 'Yes')
df.Name_intake.value_counts()

Yes    57493
No     19484
Name: Name_intake, dtype: int64

In [8]:
df.isnull().sum()

Animal ID             0
Name_intake           0
DateTime_intake       0
Found_Location        0
Intake_Type           0
IntakeCondition       0
Animal_Type_intake    0
Sex                   1
Breed_intake          0
Color_intake          0
DateTime_outcome      0
Outcome_Type          7
Sex_upon_Outcome      4
fixed_changed         0
Age_Bucket            0
DateTime_length       0
dtype: int64

In [9]:
df=df.dropna()

In [10]:
df.isnull().sum()

Animal ID             0
Name_intake           0
DateTime_intake       0
Found_Location        0
Intake_Type           0
IntakeCondition       0
Animal_Type_intake    0
Sex                   0
Breed_intake          0
Color_intake          0
DateTime_outcome      0
Outcome_Type          0
Sex_upon_Outcome      0
fixed_changed         0
Age_Bucket            0
DateTime_length       0
dtype: int64

In [11]:
# Check for duplicates rows
count=0
for i in df['Animal ID'].duplicated():
    if i is True:
        count+=1
count

19762

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 76968 entries, 0 to 76976
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Animal ID           76968 non-null  object
 1   Name_intake         76968 non-null  object
 2   DateTime_intake     76968 non-null  object
 3   Found_Location      76968 non-null  object
 4   Intake_Type         76968 non-null  object
 5   IntakeCondition     76968 non-null  object
 6   Animal_Type_intake  76968 non-null  object
 7   Sex                 76968 non-null  object
 8   Breed_intake        76968 non-null  object
 9   Color_intake        76968 non-null  object
 10  DateTime_outcome    76968 non-null  object
 11  Outcome_Type        76968 non-null  object
 12  Sex_upon_Outcome    76968 non-null  object
 13  fixed_changed       76968 non-null  int64
 14  Age_Bucket          76968 non-null  object
 15  DateTime_length     76968 non-null  object
dtypes: int64(1), object(15)
memory usage: 10.0+ MB

In [13]:
# Drop duplicates
df=df.drop_duplicates(subset='Animal ID')

In [14]:
df.head()

,Animal ID,Name_intake,DateTime_intake,Found_Location,Intake_Type,IntakeCondition,Animal_Type_intake,Sex,Breed_intake,Color_intake,DateTime_outcome,Outcome_Type,Sex_upon_Outcome,fixed_changed,Age_Bucket,DateTime_length
0,A730601,No,2016-07-07 12:11:00,1109 Shady Ln in Austin (TX),Stray,Normal,Cat,Intact Male,Domestic Shorthair Mix,Blue Tabby,2016-07-08 09:00:00,Transfer,Neutered Male,1,7-12 months,0 days 20:49:00.000000000
1,A683644,Yes,2014-07-13 11:02:00,Austin (TX),Owner Surrender,Nursing,Dog,Intact Female,Border Collie Mix,Brown/White,2014-11-06 10:06:00,Adoption,Spayed Female,1,1-6 weeks,115 days 23:04:00.000000000
2,A676515,Yes,2014-04-11 08:45:00,615 E. Wonsley in Austin (TX),Stray,Normal,Dog,Intact Male,Pit Bull Mix,White/Brown,2014-04-14 18:38:00,Return to Owner,Neutered Male,1,1-6 months,3 days 09:53:00.000000000
3,A742953,No,2017-01-31 13:30:00,S Hwy 183 And Thompson Lane in Austin (TX),Stray,Normal,Dog,Intact Male,Saluki,Sable/Cream,2017-02-04 14:17:00,Transfer,Intact Male,0,1-3 years,4 days 00:47:00.000000000
4,A679549,Yes,2014-05-22 15:43:00,124 W Anderson in Austin (TX),Stray,Normal,Cat,Intact Male,Domestic Shorthair Mix,Black/White,2014-06-16 13:54:00,Transfer,Neutered Male,1,1-6 months,24 days 22:11:00.000000000

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 57206 entries, 0 to 76975
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Animal ID           57206 non-null  object
 1   Name_intake         57206 non-null  object
 2   DateTime_intake     57206 non-null  object
 3   Found_Location      57206 non-null  object
 4   Intake_Type         57206 non-null  object
 5   IntakeCondition     57206 non-null  object
 6   Animal_Type_intake  57206 non-null  object
 7   Sex                 57206 non-null  object
 8   Breed_intake        57206 non-null  object
 9   Color_intake        57206 non-null  object
 10  DateTime_outcome    57206 non-null  object
 11  Outcome_Type        57206 non-null  object
 12  Sex_upon_Outcome    57206 non-null  object
 13  fixed_changed       57206 non-null  int64
 14  Age_Bucket          57206 non-null  object
 15  DateTime_length     57206 non-null  object
dtypes: int64(1), object(15)
memory usage: 7.4+ MB

# Outcome_Type column

In [16]:
df.head()

,Animal ID,Name_intake,DateTime_intake,Found_Location,Intake_Type,IntakeCondition,Animal_Type_intake,Sex,Breed_intake,Color_intake,DateTime_outcome,Outcome_Type,Sex_upon_Outcome,fixed_changed,Age_Bucket,DateTime_length
0,A730601,No,2016-07-07 12:11:00,1109 Shady Ln in Austin (TX),Stray,Normal,Cat,Intact Male,Domestic Shorthair Mix,Blue Tabby,2016-07-08 09:00:00,Transfer,Neutered Male,1,7-12 months,0 days 20:49:00.000000000
1,A683644,Yes,2014-07-13 11:02:00,Austin (TX),Owner Surrender,Nursing,Dog,Intact Female,Border Collie Mix,Brown/White,2014-11-06 10:06:00,Adoption,Spayed Female,1,1-6 weeks,115 days 23:04:00.000000000
2,A676515,Yes,2014-04-11 08:45:00,615 E. Wonsley in Austin (TX),Stray,Normal,Dog,Intact Male,Pit Bull Mix,White/Brown,2014-04-14 18:38:00,Return to Owner,Neutered Male,1,1-6 months,3 days 09:53:00.000000000
3,A742953,No,2017-01-31 13:30:00,S Hwy 183 And Thompson Lane in Austin (TX),Stray,Normal,Dog,Intact Male,Saluki,Sable/Cream,2017-02-04 14:17:00,Transfer,Intact Male,0,1-3 years,4 days 00:47:00.000000000
4,A679549,Yes,2014-05-22 15:43:00,124 W Anderson in Austin (TX),Stray,Normal,Cat,Intact Male,Domestic Shorthair Mix,Black/White,2014-06-16 13:54:00,Transfer,Neutered Male,1,1-6 months,24 days 22:11:00.000000000

In [17]:
df.Outcome_Type.value_counts()

Adoption           22988
Transfer           18460
Return to Owner     9806
Euthanasia          5100
Died                 533
Disposal             254
Missing               37
Rto-Adopt             15
Relocate              13
Name: Outcome_Type, dtype: int64

In [18]:
# Combine Died & Disposal Outcomes
df.loc[df.Outcome_Type == 'Disposal', 'Outcome_Type'] = 'Died'
df.Outcome_Type.value_counts()

Adoption           22988
Transfer           18460
Return to Owner     9806
Euthanasia          5100
Died                 787
Missing               37
Rto-Adopt             15
Relocate              13
Name: Outcome_Type, dtype: int64

In [19]:
# Combine Transfer & Relocate Outcomes
df.loc[df.Outcome_Type == 'Relocate', 'Outcome_Type'] = 'Transfer'
df.Outcome_Type.value_counts()

Adoption           22988
Transfer           18473
Return to Owner     9806
Euthanasia          5100
Died                 787
Missing               37
Rto-Adopt             15
Name: Outcome_Type, dtype: int64

In [20]:
#### Combine Rto-Adopt & Return to Owner
df.loc[df.Outcome_Type == 'Rto-Adopt', 'Outcome_Type'] = 'Return to Owner'
df.Outcome_Type.value_counts()

Adoption           22988
Transfer           18473
Return to Owner     9821
Euthanasia          5100
Died                 787
Missing               37
Name: Outcome_Type, dtype: int64

# DateTime_intake column

In [21]:
# Update DateTime_intake to datatime datatype
df.DateTime_intake = pd.to_datetime(df.DateTime_intake, format='%Y-%m-%d')
df.head()

,Animal ID,Name_intake,DateTime_intake,Found_Location,Intake_Type,IntakeCondition,Animal_Type_intake,Sex,Breed_intake,Color_intake,DateTime_outcome,Outcome_Type,Sex_upon_Outcome,fixed_changed,Age_Bucket,DateTime_length
0,A730601,No,2016-07-07 12:11:00,1109 Shady Ln in Austin (TX),Stray,Normal,Cat,Intact Male,Domestic Shorthair Mix,Blue Tabby,2016-07-08 09:00:00,Transfer,Neutered Male,1,7-12 months,0 days 20:49:00.000000000
1,A683644,Yes,2014-07-13 11:02:00,Austin (TX),Owner Surrender,Nursing,Dog,Intact Female,Border Collie Mix,Brown/White,2014-11-06 10:06:00,Adoption,Spayed Female,1,1-6 weeks,115 days 23:04:00.000000000
2,A676515,Yes,2014-04-11 08:45:00,615 E. Wonsley in Austin (TX),Stray,Normal,Dog,Intact Male,Pit Bull Mix,White/Brown,2014-04-14 18:38:00,Return to Owner,Neutered Male,1,1-6 months,3 days 09:53:00.000000000
3,A742953,No,2017-01-31 13:30:00,S Hwy 183 And Thompson Lane in Austin (TX),Stray,Normal,Dog,Intact Male,Saluki,Sable/Cream,2017-02-04 14:17:00,Transfer,Intact Male,0,1-3 years,4 days 00:47:00.000000000
4,A679549,Yes,2014-05-22 15:43:00,124 W Anderson in Austin (TX),Stray,Normal,Cat,Intact Male,Domestic Shorthair Mix,Black/White,2014-06-16 13:54:00,Transfer,Neutered Male,1,1-6 months,24 days 22:11:00.000000000

# DateTime_outcome column

In [22]:
# Update DateTime_outcome to datatime datatype
df.DateTime_outcome = pd.to_datetime(df.DateTime_outcome, format='%Y-%m-%d')
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 57206 entries, 0 to 76975
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Animal ID           57206 non-null  object
 1   Name_intake         57206 non-null  object
 2   DateTime_intake     57206 non-null  datetime64[ns]
 3   Found_Location      57206 non-null  object
 4   Intake_Type         57206 non-null  object
 5   IntakeCondition     57206 non-null  object
 6   Animal_Type_intake  57206 non-null  object
 7   Sex                 57206 non-null  object
 8   Breed_intake        57206 non-null  object
 9   Color_intake        57206 non-null  object
 10  DateTime_outcome    57206 non-null  datetime64[ns]
 11  Outcome_Type        57206 non-null  object
 12  Sex_upon_Outcome    57206 non-null  object
 13  fixed_changed       57206 non-null  int64
 14  Age_Bucket          57206 non-null  object
 15  DateTime_length     57206 non-null  object
dtypes: datetime64[ns](2), int64(1), object(13)
memory usage: 7.4+ MB

# DateTime_length column

In [23]:
# Create a new column and calculate the length of stay
df['datetime_length']=df['DateTime_outcome']-df['DateTime_intake']
df.head()

,Animal ID,Name_intake,DateTime_intake,Found_Location,Intake_Type,IntakeCondition,Animal_Type_intake,Sex,Breed_intake,Color_intake,DateTime_outcome,Outcome_Type,Sex_upon_Outcome,fixed_changed,Age_Bucket,DateTime_length,datetime_length
0,A730601,No,2016-07-07 12:11:00,1109 Shady Ln in Austin (TX),Stray,Normal,Cat,Intact Male,Domestic Shorthair Mix,Blue Tabby,2016-07-08 09:00:00,Transfer,Neutered Male,1,7-12 months,0 days 20:49:00.000000000,0 days 20:49:00
1,A683644,Yes,2014-07-13 11:02:00,Austin (TX),Owner Surrender,Nursing,Dog,Intact Female,Border Collie Mix,Brown/White,2014-11-06 10:06:00,Adoption,Spayed Female,1,1-6 weeks,115 days 23:04:00.000000000,115 days 23:04:00
2,A676515,Yes,2014-04-11 08:45:00,615 E. Wonsley in Austin (TX),Stray,Normal,Dog,Intact Male,Pit Bull Mix,White/Brown,2014-04-14 18:38:00,Return to Owner,Neutered Male,1,1-6 months,3 days 09:53:00.000000000,3 days 09:53:00
3,A742953,No,2017-01-31 13:30:00,S Hwy 183 And Thompson Lane in Austin (TX),Stray,Normal,Dog,Intact Male,Saluki,Sable/Cream,2017-02-04 14:17:00,Transfer,Intact Male,0,1-3 years,4 days 00:47:00.000000000,4 days 00:47:00
4,A679549,Yes,2014-05-22 15:43:00,124 W Anderson in Austin (TX),Stray,Normal,Cat,Intact Male,Domestic Shorthair Mix,Black/White,2014-06-16 13:54:00,Transfer,Neutered Male,1,1-6 months,24 days 22:11:00.000000000,24 days 22:11:00

In [24]:
# Check values for datetime_length column
df['datetime_length'].value_counts()

0 days 00:14:00       72
0 days 00:08:00       64
0 days 00:19:00       64
0 days 00:45:00       64
0 days 00:11:00       63
                      ..
69 days 10:15:00       1
63 days 00:01:00       1
-36 days +03:35:00     1
2 days 03:43:00        1
0 days 00:00:00        1
Name: datetime_length, Length: 25060, dtype: int64

## delete all negative values

In [25]:
# Create a temporary 'int' column and convert datetime to int
df['int'] = df['datetime_length'].astype(np.int64)

In [26]:
df['int'].value_counts()

 840000000000        72
 480000000000        64
 1140000000000       64
 2700000000000       64
 660000000000        63
                     ..
 5998500000000000     1
 5443260000000000     1
-3097500000000000     1
 186180000000000      1
 0                    1
Name: int, Length: 25060, dtype: int64

In [27]:
# replace negative values to nan
df.loc[df.int < 0, 'int'] = None

In [28]:
# Check for null values
df.isnull().sum()

Animal ID                0
Name_intake              0
DateTime_intake          0
Found_Location           0
Intake_Type              0
IntakeCondition          0
Animal_Type_intake       0
Sex                      0
Breed_intake             0
Color_intake             0
DateTime_outcome         0
Outcome_Type             0
Sex_upon_Outcome         0
fixed_changed            0
Age_Bucket               0
DateTime_length          0
datetime_length          0
int                   1400
dtype: int64

In [29]:
# drop null values
df=df.dropna()

In [30]:
# drop temporary 'int' column and original DateTime_length column
df=df.drop(columns=['int','DateTime_length'])

# Rename calculated length of stay column
df.rename(columns = {'datetime_length':'DateTime_length'}, inplace = True)

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 55806 entries, 0 to 76975
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Animal ID           55806 non-null  object
 1   Name_intake         55806 non-null  object
 2   DateTime_intake     55806 non-null  datetime64[ns]
 3   Found_Location      55806 non-null  object
 4   Intake_Type         55806 non-null  object
 5   IntakeCondition     55806 non-null  object
 6   Animal_Type_intake  55806 non-null  object
 7   Sex                 55806 non-null  object
 8   Breed_intake        55806 non-null  object
 9   Color_intake        55806 non-null  object
 10  DateTime_outcome    55806 non-null  datetime64[ns]
 11  Outcome_Type        55806 non-null  object
 12  Sex_upon_Outcome    55806 non-null  object
 13  fixed_changed       55806 non-null  int64
 14  Age_Bucket          55806 non-null  object
 15  DateTime_length     55806 non-null  timedelta64[ns]
dtypes: datetime64[ns](2), int64(1), object(12), timedelta64[ns](1)
memory usage: 7.2+ MB

In [32]:
df.head(10)

,Animal ID,Name_intake,DateTime_intake,Found_Location,Intake_Type,IntakeCondition,Animal_Type_intake,Sex,Breed_intake,Color_intake,DateTime_outcome,Outcome_Type,Sex_upon_Outcome,fixed_changed,Age_Bucket,DateTime_length
0,A730601,No,2016-07-07 12:11:00,1109 Shady Ln in Austin (TX),Stray,Normal,Cat,Intact Male,Domestic Shorthair Mix,Blue Tabby,2016-07-08 09:00:00,Transfer,Neutered Male,1,7-12 months,0 days 20:49:00
1,A683644,Yes,2014-07-13 11:02:00,Austin (TX),Owner Surrender,Nursing,Dog,Intact Female,Border Collie Mix,Brown/White,2014-11-06 10:06:00,Adoption,Spayed Female,1,1-6 weeks,115 days 23:04:00
2,A676515,Yes,2014-04-11 08:45:00,615 E. Wonsley in Austin (TX),Stray,Normal,Dog,Intact Male,Pit Bull Mix,White/Brown,2014-04-14 18:38:00,Return to Owner,Neutered Male,1,1-6 months,3 days 09:53:00
3,A742953,No,2017-01-31 13:30:00,S Hwy 183 And Thompson Lane in Austin (TX),Stray,Normal,Dog,Intact Male,Saluki,Sable/Cream,2017-02-04 14:17:00,Transfer,Intact Male,0,1-3 years,4 days 00:47:00
4,A679549,Yes,2014-05-22 15:43:00,124 W Anderson in Austin (TX),Stray,Normal,Cat,Intact Male,Domestic Shorthair Mix,Black/White,2014-06-16 13:54:00,Transfer,Neutered Male,1,1-6 months,24 days 22:11:00
5,A683798,Yes,2016-07-21 12:16:00,3118 Windsor Rd in Austin (TX),Stray,Normal,Cat,Spayed Female,Domestic Medium Hair Mix,White/Black,2016-10-18 10:55:00,Adoption,Spayed Female,0,1-3 years,88 days 22:39:00
9,A683656,No,2014-07-13 13:20:00,8238 Research Blvd in Austin (TX),Stray,Normal,Cat,Intact Male,Snowshoe Mix,Lynx Point,2014-07-17 16:57:00,Adoption,Neutered Male,1,1-6 months,4 days 03:37:00
10,A709749,Yes,2015-08-12 18:29:00,4800 Weletka Dr in Austin (TX),Stray,Normal,Cat,Intact Female,Domestic Shorthair Mix,Calico,2015-09-22 12:49:00,Transfer,Spayed Female,1,1-3 years,40 days 18:20:00
11,A692161,Yes,2014-11-15 15:18:00,Avenue G/42Nd in Austin (TX),Owner Surrender,Normal,Dog,Intact Male,Pit Bull Mix,Brown/White,2014-11-21 18:55:00,Adoption,Neutered Male,1,1-6 months,6 days 03:37:00
12,A733551,Yes,2016-08-23 14:35:00,183 And Cameron in Austin (TX),Stray,Normal,Cat,Intact Male,Domestic Shorthair Mix,Brown Tabby/White,2016-09-01 00:00:00,Transfer,Intact Male,0,1-6 months,8 days 09:25:00

# Intake condition column

In [33]:
df.IntakeCondition.value_counts()

Normal      48329
Injured      3022
Sick         2456
Nursing      1523
Aged          250
Other         112
Feral          72
Pregnant       42
Name: IntakeCondition, dtype: int64

In [34]:
# Combine Aged and Feral with Other for IntakeCondition
df.loc[(df.IntakeCondition == 'Aged') | (df.IntakeCondition == 'Feral'), 'IntakeCondition'] = 'Other'

In [35]:
# Combine Injured and Sick for Intake Condition
df.loc[(df.IntakeCondition == 'Injured') | (df.IntakeCondition == 'Sick'), 'IntakeCondition'] = 'Medical'

In [36]:
# Combine Pregnant and Nursing for  IntakeCondition
df.loc[(df.IntakeCondition == 'Nursing') | (df.IntakeCondition == 'Pregnant'), 'IntakeCondition' ] = 'Maternity'
df.IntakeCondition.value_counts()

Normal       48329
Medical       5478
Maternity     1565
Other          434
Name: IntakeCondition, dtype: int64

# Animal_Type_intake column

In [37]:
df.Animal_Type_intake.value_counts()

Dog          30040
Cat          22059
Other         3449
Bird           250
Livestock        8
Name: Animal_Type_intake, dtype: int64

In [38]:
# Combine Bird and Livestock with Other for Animal_Type_intake
df.loc[(df.Animal_Type_intake == 'Bird') | (df.Animal_Type_intake == 'Livestock'), 'Animal_Type_intake'] = 'Other'
df.Animal_Type_intake.value_counts()

Dog      30040
Cat      22059
Other     3707
Name: Animal_Type_intake, dtype: int64

# Sex column

In [39]:
df.Sex.value_counts()

Intact Male      18780
Intact Female    17711
Neutered Male     7301
Spayed Female     6476
Unknown           5538
Name: Sex, dtype: int64

In [40]:
df.rename(columns={'Sex': 'Sex_Intake'}, inplace=True)

# Sex_upon_Outcome

In [41]:
df.Sex_upon_Outcome.value_counts()

Neutered Male    18906
Spayed Female    17201
Intact Male       7175
Intact Female     6986
Unknown           5538
Name: Sex_upon_Outcome, dtype: int64

# Found_Location column

In [42]:
counts=df['Found_Location'].value_counts()
counts

Austin (TX)                                8896
Travis (TX)                                 587
7201 Levander Loop in Austin (TX)           406
Del Valle (TX)                              275
Outside Jurisdiction                        271
                                           ...
1104 Strickling Dr in Pflugerville (TX)       1
2608 Rogers Ave in Austin (TX)                1
845 N Meadows Dr #A in Austin (TX)            1
10020 Hiddden Meadow in Austin (TX)           1
1800 Lavaca St in Austin (TX)                 1
Name: Found_Location, Length: 27060, dtype: int64

In [43]:
new_location=[]
for i in df['Found_Location']:
    if ' in' in i and i.split()[0].isdigit() == True:
            i=i
    else:
        i=np.nan
    new_location.append(i)

In [44]:
new_location

['1109 Shady Ln in Austin (TX)',
 nan,
 '615 E. Wonsley in Austin (TX)',
 nan,
 '124 W Anderson in Austin (TX)',
 '3118 Windsor Rd in Austin (TX)',
 '8238 Research Blvd in Austin (TX)',
 '4800 Weletka Dr in Austin (TX)',
 nan,
 '183 And Cameron in Austin (TX)',
 '6808 S Ih 35 Frontage Rd in Austin (TX)',
 '8413 Danville Dr in Austin (TX)',
 '11602 Gunsmoke Circle in Austin (TX)',
 '2940 Eckert St in Austin (TX)',
 nan,
 nan,
 nan,
 '1506 Thorneridge Road in Austin (TX)',
 nan,
 '1830 W Rundberg Ln in Austin (TX)',
 nan,
 nan,
 '9308 N Lamar in Austin (TX)',
 nan,
 nan,
 '1128 Spur in Austin (TX)',
 nan,
 '12505 Rampart St in Austin (TX)',
 '4502 Hudson Bend Rd in Travis (TX)',
 nan,
 '609 W Lynn St #1 in Austin (TX)',
 '704 Hyde Park Ct in Austin (TX)',
 '13096 N 183 in Austin (TX)',
 '701 W Longspur in Austin (TX)',
 nan,
 nan,
 '2203 Singletree Ave in Austin (TX)',
 nan,
 '11417 Trails End in Travis (TX)',
 nan,
 '7607 Glen Hill Cove in Austin (TX)',
 '2202 Galway St in Austin (TX)',
 nan,
 '12034 Research in Austin (TX)',
 nan,
 '120 Webberwood Way in Travis (TX)',
 nan,
 nan,
 '5446 Walnut Grove in Austin (TX)',
 nan,
 '7201 Levander Loop in Austin (TX)',
 '11351 Bradshaw Rd in Austin (TX)',
 '10300 Doyle Rd in Del Valle (TX)',
 nan,
 '9300 Northgate Blvd in Austin (TX)',
 '14904 Valerian in Travis (TX)',
 nan,
 nan,
 nan,
 '1603 Cricket Hollow Drive in Austin (TX)',
 '10714 San Jose in Travis (TX)',
 '900 Chicon St in Austin (TX)',
 nan,
 '7100 Northeast Dr in Austin (TX)',
 nan,
 nan,
 '10223 Thaxton in Austin (TX)',
 '7112 Hillcroft Dr in Austin (TX)',
 '1704 Citation Dr in Austin (TX)',
 nan,
 '5200 Ravensdale in Austin (TX)',
 '9101 Sweet Gum Dr in Austin (TX)',
 '9920 Qual Blvd in Austin (TX)',
 '1310 Delano St in Austin (TX)',
 '5702 Richmond Ave in Austin (TX)',
 '9611 Decker Lake Rd in Travis (TX)',
 '6806 Thistle Hill Way in Travis (TX)',
 nan,
 nan,
 '5338 Thunder Creek in Austin (TX)',
 nan,
 nan,
 '13424 Clara Martin in Travis (TX)',
 nan,
 '973 & 183 in Travis (TX)',
 '124 W Anderson Ln in Austin (TX)',
 '2510 Lehigh Dr in Austin (TX)',
 nan,
 '13676 Bee Cave Pkwy in Bee Cave (TX)',
 '3101 Yellowpine Ter in Austin (TX)',
 nan,
 nan,
 '7132 Texas 71 in Austin (TX)',
 nan,
 '1904 Poquito in Austin (TX)',
 nan,
 '12304 Willow Wild Dr in Austin (TX)',
 nan,
 nan,
 '1109 S Pleasant Valley in Austin (TX)',
 nan,
 '1301 Spyglass Drive in Austin (TX)',
 nan,
 nan,
 nan,
 '4601 Tuckerhill Lane in Travis (TX)',
 '7201 Levander Loop in Austin (TX)',
 '3300 Killingsworth in Travis (TX)',
 '7904 Fm 969 in Austin (TX)',
 nan,
 '911 Battle Bend Blvd in Austin (TX)',
 nan,
 '6700 Meadow Lake in Austin (TX)',
 nan,
 '11113 Research Blvd in Austin (TX)',
 nan,
 '4215 Caldwell Ln in Del Valle (TX)',
 '11400 Concordia University Dr. in Austin (TX)',
 nan,
 nan,
 '19211 Blake Manor Rd in Manor (TX)',
 '14100 Thermal Driver in Austin (TX)',
 nan,
 nan,
 nan,
 '12027 Bethel Church Rd. in Travis (TX)',
 '71 & Spirt Of Texas Hwy in Austin (TX)',
 '7201 Levander Loop in Austin (TX)',
 nan,
 '8724 Birmingham in Austin (TX)',
 '1300 Fm 812 in Austin (TX)',
 '13021 Dessau Rd in Travis (TX)',
 nan,
 nan,
 nan,
 '13924 Marcella in Travis (TX)',
 nan,
 '1517 Geoffs Dr in Austin (TX)',
 nan,
 '9805 Bal Harbor in Travis (TX)',
 nan,
 '509 Montopolis Dr in Austin (TX)',
 '3400 S Congress Ave in Austin (TX)',
 '8900 Coulver Rd in Travis (TX)',
 '5400 Pecan Brook in Austin (TX)',
 '1420 E Wells Branch Pkwy in Austin (TX)',
 '11601 Domain Dr in Austin (TX)',
 nan,
 nan,
 '710 E Ben White Blvd in Austin (TX)',
 nan,
 '9913 Morgan Creek Dr in Austin (TX)',
 '12508 Esplanade St in Austin (TX)',
 nan,
 '1457 W Pecan St in Pflugerville (TX)',
 '107 E. Wheeler St in Manor (TX)',
 '1511 Faro Drive in Austin (TX)',
 '10928 Desert Willow Dr in Austin (TX)',
 '5365 Westminster Ave in Austin (TX)',
 nan,
 '124 W Anderson Ln in Austin (TX)',
 '11100 Metric in Austin (TX)',
 '6205 Marigold in Austin (TX)',
 '9505 Stonelake Blvd in Austin (TX)',
 nan,
 '9515 Hotel Dr in Austin (TX)',
 '6302 Salcon Cliff Dr in Austin (TX)',
 nan,
 '6600 Elm Creek Dr # 65 in Austin (TX)',
 nan,
 nan,
 nan,
 '4900 Gonzales St in Austin (TX)',
 '4902 Teri Rd in Austin (TX)',
 '8800 N Ih 35 in Austin (TX)',
 nan,
 nan,
 '9705 Manchaca Rd in Austin (TX)',
 '8824 Stanbourne in Austin (TX)',
 nan,
 nan,
 nan,
 '4434 Frontier Trl( Goodsam Didnt Leave Found Address in Austin (TX)',
 nan,
 nan,
 '213 W Wild Sena in Austin (TX)',
 '12151 Ih 35 in Austin (TX)',
 nan,
 '812 Springdale Rd in Austin (TX)',
 nan,
 '9802 Roxanna Drive in Austin (TX)',
 nan,
 '7513 N Interstate Hwy 35 in Austin (TX)',
 '10707 Lake Creek Parkway in Austin (TX)',
 nan,
 nan,
 nan,
 '4707 Munson in Austin (TX)',
 '5400 Springville Ln in Austin (TX)',
 '7404 Southgate Ln in Austin (TX)',
 '3005 Parker Lane in Austin (TX)',
 '7500 Blessing in Austin (TX)',
 '9601 Point Vista Pl in Austin (TX)',
 '5808 Mckinney Falls Parkway in Austin (TX)',
 nan,
 nan,
 nan,
 '8003 Decker Ln in Travis (TX)',
 '12302 Havelock Dr in Austin (TX)',
 '1406 Click Cv in Austin (TX)',
 '13521 Sea Biscuit in Del Valle (TX)',
 '1114 Henninger St in Austin (TX)',
 nan,
 '816 E. 49Th in Austin (TX)',
 '6633 E 290 in Austin (TX)',
 nan,
 '8001 S Ih 35 Frontage Rd in Austin (TX)',
 nan,
 nan,
 '8408 Riverstone in Austin (TX)',
 nan,
 nan,
 '7309 Brookhollow Dr in Austin (TX)',
 nan,
 nan,
 '509 E Todd Lane in Austin (TX)',
 nan,
 '610 Wilmes Dr in Austin (TX)',
 nan,
 nan,
 '4801 S Ih 35 in Austin (TX)',
 '1000 E. 41St St. in Austin (TX)',
 '11610 Prairie Hen Ln in Austin (TX)',
 '2000 Burton Dr in Austin (TX)',
 '11702 Brookwood in Austin (TX)',
 nan,
 '124 W Anderson Ln in Austin (TX)',
 '11351 Bradshaw Rd in Austin (TX)',
 '11503 Parsons Rd in Travis (TX)',
 nan,
 nan,
 nan,
 nan,
 '4410 Dovemeadow Dr in Austin (TX)',
 nan,
 '177 Meadow View Blvd in Del Valle (TX)',
 '1303 Parsons A in Austin (TX)',
 '17005 Hayride Cir in Del Valle (TX)',
 '8609 Alpine Dr in Del Valle (TX)',
 nan,
 nan,
 '124 W Anderson Ln in Austin (TX)',
 nan,
 '5932 Hammermill Run in Austin (TX)',
 nan,
 '301 Twin Creeks Rd in Travis (TX)',
 '2210 E 9Th St Unit C in Austin (TX)',
 '1412 Norseman Terrace in Austin (TX)',
 nan,
 '12401 Pauls Valley Rd in Austin (TX)',
 '12034 Research Blvd in Austin (TX)',
 '985112001282540 in Austin (TX)',
 '5301 Fort Clark Dr in Austin (TX)',
 '21413 Webber Oaks Cv in Travis (TX)',
 nan,
 nan,
 '13904 Old Hwy 20 in Manor (TX)',
 nan,
 '407 Meadow Lea Dr in Austin (TX)',
 '17944 Majestic Elm Ln in Travis (TX)',
 nan,
 '5106 Meadow Creek Cove in Austin (TX)',
 nan,
 '12118 Walnut Park #828 in Austin (TX)',
 '11123 Old Lockhart Rd in Austin (TX)',
 '3206 East 16Th in Austin (TX)',
 '9001 N 620 in Austin (TX)',
 nan,
 '21069 Blake Manor Rd in Travis (TX)',
 '9401 Roanna Dr in Austin (TX)',
 nan,
 '1800 Crystal Bend in Travis (TX)',
 '1200 W Saint Johns in Austin (TX)',
 '420 W Slaughter in Austin (TX)',
 '2200 Berkeley Ave in Austin (TX)',
 '13 Club Estates in Lakeway (TX)',
 '412 E William Cannon Dr in Austin (TX)',
 '1820 Kenwood Ave in Austin (TX)',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '2300 East 2Nd St in Austin (TX)',
 nan,
 nan,
 nan,
 nan,
 '5912 Marilyn Dr in Austin (TX)',
 '6203 Saddler Ln in Austin (TX)',
 '2700 West Pecan St in Travis (TX)',
 '2400 Grove Blvd in Austin (TX)',
 '9011 Briardale Dr in Austin (TX)',
 nan,
 nan,
 '9300 S Ih 35 Frontage Rd in Austin (TX)',
 '8202 Furness Cv in Austin (TX)',
 nan,
 '1901 E Anderson Ln in Austin (TX)',
 '5917 Little Creek Trail in Austin (TX)',
 '7201 Levander Loop in Austin (TX)',
 nan,
 nan,
 '12401 N Lamar in Austin (TX)',
 '3112 Speidel Dr in Austin (TX)',
 '512 W Stassney in Austin (TX)',
 nan,
 nan,
 '900 Broken Feather Trl in Austin (TX)',
 nan,
 '7201 Levander in Austin (TX)',
 '923 Walter St in Austin (TX)',
 '5111 Single Shot in Austin (TX)',
 '12300 Hymeadow Dr. #307 in Austin (TX)',
 nan,
 '5214 Duval Rd in Austin (TX)',
 nan,
 nan,
 '2900 Sunridge Drive Bldg 13 in Austin (TX)',
 nan,
 '103 W Odell St in Austin (TX)',
 nan,
 '12304 Elm Valley Dr in Travis (TX)',
 '3811 E 12Th St in Austin (TX)',
 nan,
 nan,
 '4108 Nixon Ln in Austin (TX)',
 nan,
 '2309 Berkeley #1085 in Austin (TX)',
 '1228 Eleanor St in Austin (TX)',
 '7310 Meador Ave in Austin (TX)',
 nan,
 '2201 Barton Springs Rd in Austin (TX)',
 nan,
 '11729 Lime Creek Road in Leander (TX)',
 '5300 Jimmy Clay Drive in Austin (TX)',
 '2900 Sunridge Dr in Austin (TX)',
 '1303 Bob Harrison in Austin (TX)',
 nan,
 '220 Pompton Dr in Austin (TX)',
 nan,
 '13212 High Sierra St in Manor (TX)',
 '1317 W. 10Th in Austin (TX)',
 '4534 Westgate Blvd in Austin (TX)',
 '2209 Kinney in Austin (TX)',
 '2205 Voyageurs in Austin (TX)',
 '6403 Farmdale Ln in Austin (TX)',
 '13802 Hokanson Rd in Travis (TX)',
 '4216 S Congress Ave in Austin (TX)',
 nan,
 '2100 Barton Springs Rd in Austin (TX)',
 nan,
 nan,
 nan,
 '1704 Perez in Austin (TX)',
 nan,
 nan,
 nan,
 '9100 Evelyn Rd in Travis (TX)',
 nan,
 '1911 Willow Creek Dr in Austin (TX)',
 '10135 Lake Creek Pkwy in Austin (TX)',
 '2302 Bahama Rd in Travis (TX)',
 nan,
 '10427 Kirken St in Austin (TX)',
 nan,
 nan,
 '8028 Elroy Rd in Travis (TX)',
 nan,
 '310 Blackson Ave in Austin (TX)',
 nan,
 '13309 Bennington Ln in Austin (TX)',
 '810 E Slaughter Ln 9102 in Austin (TX)',
 '11604 Ranch House Cv in Travis (TX)',
 '8601 Vertex in Austin (TX)',
 '16808 High Noon in Del Valle (TX)',
 nan,
 '2507 Bitter Creek in Austin (TX)',
 '7917 Brockman St in Austin (TX)',
 '409 Covenant Canyon Trl in Austin (TX)',
 '5702 Richmond Ave in Austin (TX)',
 '9219 Anderson Mill in Austin (TX)',
 nan,
 '7903 Taza Trl in Austin (TX)',
 nan,
 nan,
 '6500 River Place Blvd in Austin (TX)',
 '12320 Dessau Road in Austin (TX)',
 '2202 Cedar Bend Dr # B in Austin (TX)',
 '4106 N Lamar Blvd in Austin (TX)',
 nan,
 '16801 Trevin Cv in Manor (TX)',
 '4101 Smith School Road in Austin (TX)',
 '2703 Channing Cir in Austin (TX)',
 '1701 Congress Ave in Austin (TX)',
 '2121 Rivena Dr in Austin (TX)',
 '4604 Reyes St in Austin (TX)',
 '2000 E. 8Th in Austin (TX)',
 '11404 Briarcreek Loop in Travis (TX)',
 nan,
 nan,
 '2000 Millhouse Dr in Travis (TX)',
 '3101 Oak Springs Dr in Austin (TX)',
 '9700 Mv Neil Dr in Travis (TX)',
 nan,
 nan,
 '7500 S I H 35 in Austin (TX)',
 nan,
 '5947 Hammermill Run in Austin (TX)',
 '2504 New York Dr # 134 in Austin (TX)',
 nan,
 nan,
 nan,
 '1710 Eastside Dr in Austin (TX)',
 '4500 Steiner in Austin (TX)',
 nan,
 nan,
 nan,
 '4606 Molera in Austin (TX)',
 '4434 Frontier Trl in Austin (TX)',
 '9117 Anderson Mill Rd in Austin (TX)',
 nan,
 nan,
 nan,
 '1403 Bentwood Rd in Austin (TX)',
 nan,
 '19379 Wilkey Lane in Pflugerville (TX)',
 nan,
 nan,
 '22900 Big Sandy Dr in Leander (TX)',
 '2400 E Cesar Chavez St in Austin (TX)',
 nan,
 nan,
 nan,
 '5500 Ross Rd in Austin (TX)',
 nan,
 nan,
 '3611 Brifal Path in Austin (TX)',
 '2909 Thurgood Ave in Austin (TX)',
 '6001 Shepherd Mountian Cv in Austin (TX)',
 '1601 E Slaughter Ln #514 in Austin (TX)',
 '1221 West Ben White in Austin (TX)',
 '2209 Rutland Dr, Unit B in Austin (TX)',
 '309 Thelma Drive in Austin (TX)',
 '1206 Blackfoot in Austin (TX)',
 nan,
 '1000 W Rundberg Ln in Austin (TX)',
 '9700 Teasdale in Austin (TX)',
 nan,
 nan,
 nan,
 '3005 S. Lamar in Austin (TX)',
 nan,
 '139 Bolles Cicrle in Austin (TX)',
 '5905 Lookout Mountain Dr in Austin (TX)',
 '5903 Wideleaf in Austin (TX)',
 '11919 Manchaca Rd in Austin (TX)',
 '4709 Lake George Ln in Austin (TX)',
 '3201 Duval Rd in Austin (TX)',
 nan,
 '2500 Magin Meadow Dr in Austin (TX)',
 '12401 Pauls Valley Rd in Austin (TX)',
 nan,
 nan,
 nan,
 '11900 Buckingham Rd in Austin (TX)',
 '1203 Springdale Rd in Austin (TX)',
 '2614 Howellwood Way in Austin (TX)',
 '6003 Bull Creek Rd in Austin (TX)',
 '4019 Far West Blvd in Austin (TX)',
 nan,
 nan,
 '7905 Briarton Dr in Austin (TX)',
 '11800 Pinto Circle in Travis (TX)',
 nan,
 nan,
 nan,
 nan,
 nan,
 '3002 Ellon Rd in Del Valle (TX)',
 nan,
 nan,
 nan,
 nan,
 '916 Reseach Blvd in Austin (TX)',
 nan,
 nan,
 '8519 Cahill Dr in Austin (TX)',
 '14909 Cordero Dr in Austin (TX)',
 '515 Congress Ave in Austin (TX)',
 '20412 Ed Acklin Rd in Manor (TX)',
 '2941 Moss St in Austin (TX)',
 nan,
 nan,
 '12036 Parsons Rd in Travis (TX)',
 '7500 S Pleasant Valley Rd in Austin (TX)',
 nan,
 nan,
 nan,
 '9401 S Hwy 183 in Travis (TX)',
 nan,
 '2347 Douglas #1103 in Austin (TX)',
 nan,
 '1111 Lawson in Austin (TX)',
 '1221 Southport Dr in Austin (TX)',
 nan,
 '5114 Turnstone Dr in Austin (TX)',
 nan,
 '5904 E Stassney in Austin (TX)',
 nan,
 '11604 Loweswater in Austin (TX)',
 '2702 Rae Dell Ave in Austin (TX)',
 '308 Le Grande Ave in Austin (TX)',
 '5416 Marlborough Dr in Austin (TX)',
 '6719 N Lamar Blvd in Austin (TX)',
 nan,
 '2505 Inwood Pl in Austin (TX)',
 nan,
 '6700 Evelyn Rd in Austin (TX)',
 '2048 W Stassney Ln in Austin (TX)',
 '4434 Frontier in Austin (TX)',
 '3001 Yandall in Austin (TX)',
 '124 West Anderson Lane in Austin (TX)',
 '7619 Scenic Brook in Austin (TX)',
 '4924 Craigwood And Fm 969 in Austin (TX)',
 '6600 Elm Creek in Austin (TX)',
 '528 S Meadowlark St in Austin (TX)',
 nan,
 '1912 E William Cannon Dr in Austin (TX)',
 nan,
 nan,
 nan,
 nan,
 '124 W Anderson Ln in Austin (TX)',
 nan,
 nan,
 nan,
 '2000 N. Ih35 in Austin (TX)',
 '2816 E 12Th St in Austin (TX)',
 nan,
 nan,
 nan,
 '6311 Colina Ln in Austin (TX)',
 '14908 Fagerquist Rd in Austin (TX)',
 '1412 Orange Spice Ct in Travis (TX)',
 '2336 Douglas St in Austin (TX)',
 '9206 Spring Hollow Dr in Austin (TX)',
 '1156 W Cesar Chavez St in Austin (TX)',
 '900 Ruth Ave in Austin (TX)',
 '7201 Levander Loop in Austin (TX)',
 nan,
 '1157 Salina St in Austin (TX)',
 '12034 Research Blvd in Austin (TX)',
 '3400 South Congress in Austin (TX)',
 '14100 Briarcreek Loop in Travis (TX)',
 nan,
 nan,
 '5010 Old Manor Rd. in Austin (TX)',
 '831 B N Meadows in Austin (TX)',
 '12120 Manchaca Rd in Austin (TX)',
 '1600 Wells Branch Pkwy in Austin (TX)',
 '124 W Anderson Ln in Austin (TX)',
 nan,
 '9503 Queenswood Dr in Austin (TX)',
 '1135 Don Ann St in Austin (TX)',
 nan,
 '605 Park Blvd in Austin (TX)',
 '2338 Wilson St in Austin (TX)',
 '15200 Anderson Mill Rd in Travis (TX)',
 '7612 Marl in Austin (TX)',
 nan,
 nan,
 '3500 N Capital Of Texas Hwy in Austin (TX)',
 '1300 Crossing Place in Austin (TX)',
 '14400 Harris Ridge Blvd in Pflugerville (TX)',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '6207 Vera Ln in Austin (TX)',
 '1213 Mathias St in Austin (TX)',
 '6101 Landscape in Austin (TX)',
 nan,
 '7001 Circle S Rd in Austin (TX)',
 '4800 Eilers Rd in Austin (TX)',
 nan,
 '4610 Avenue D in Austin (TX)',
 nan,
 '6808 Mira Loma Ln in Austin (TX)',
 '1600 Ih 35 in Austin (TX)',
 '8805 N Plaza Ct in Austin (TX)',
 '1000 Ellingson Ln in Austin (TX)',
 nan,
 '3001 S Congress Ave in Austin (TX)',
 '5904 Dunbury Dr in Austin (TX)',
 nan,
 '11193 Lambert Ln in Austin (TX)',
 '10601 Manchaca in Austin (TX)',
 '9500 W Parmer Ln in Austin (TX)',
 '5304 Great Divide Dr in Bee Cave (TX)',
 nan,
 '12737 Magnolia Mound Trl in Austin (TX)',
 '3302 Northeast Dr in Austin (TX)',
 '3016 Fm 1327 Land Fill in Austin (TX)',
 nan,
 '107 Beaver in Austin (TX)',
 nan,
 nan,
 '8901 Viking in Austin (TX)',
 '1616 Webberville #A in Austin (TX)',
 nan,
 '4106 N Lamar in Austin (TX)',
 '9414 N Lamar in Austin (TX)',
 '1748 Ohlen Rd #98 in Austin (TX)',
 nan,
 '7300 West Rim Rd in Austin (TX)',
 '5701 Johnny Morris Rd in Austin (TX)',
 nan,
 '4502 Acres Ln in Austin (TX)',
 '12034 Research Blvd in Austin (TX)',
 '1317 Exposition Blvd in Austin (TX)',
 nan,
 '6318 Del Monte in Austin (TX)',
 '91217 Lowden Ln in Travis (TX)',
 nan,
 '1402 E St Johns Ave in Austin (TX)',
 '1015 E Yager in Austin (TX)',
 '704 Franklin in Austin (TX)',
 '7209 Wild Onion in Austin (TX)',
 '4106 N Lamar in Austin (TX)',
 '3600 Presidential Blvd in Austin (TX)',
 nan,
 nan,
 nan,
 nan,
 '6913 Langston Dr in Austin (TX)',
 '1601 E Slaughter Ln in Austin (TX)',
 '4434 Frontier Blvd in Austin (TX)',
 '7809 E Ben White Blvd in Austin (TX)',
 '909 Navasota St in Austin (TX)',
 '810 E Slaughter Ln in Austin (TX)',
 '5604 Hudson St in Austin (TX)',
 '1618 Ashberry Dr in Austin (TX)',
 '3819 Southway Dr in Austin (TX)',
 nan,
 '3502 Needls Dr in Austin (TX)',
 nan,
 '3816 Leafield Drive in Austin (TX)',
 '13420 Breezy Meadow Lane in Manor (TX)',
 nan,
 nan,
 '6704 Manchaca Rd in Austin (TX)',
 '6907 Convict Hill Rd in Austin (TX)',
 nan,
 '18417 Plazaway in Jonestown (TX)',
 nan,
 '6607 Brodie Ln in Austin (TX)',
 '12529 Sky Harbor Drive in Del Valle (TX)',
 nan,
 '2809 Parker Ln in Austin (TX)',
 '1400 Cardinal Hill Dr in Austin (TX)',
 '3001 S Congress in Austin (TX)',
 '8023 Coulver in Austin (TX)',
 '11900 Athens St in Manor (TX)',
 '12901 N 35 in Austin (TX)',
 nan,
 nan,
 '4605 Button Bend Rd in Austin (TX)',
 nan,
 '12800  Thome Valley Dr in Del Valle (TX)',
 '8900 Shoalcreek Blvd in Austin (TX)',
 '21413 Webber Oaks Cv in Travis (TX)',
 '5761 Palo Blanco Dr in Austin (TX)',
 nan,
 '1156 W Cesar Chavez St in Austin (TX)',
 nan,
 '7905 San Felipe #124 in Austin (TX)',
 nan,
 '1300 Mckie in Austin (TX)',
 nan,
 nan,
 nan,
 '1509 38 Half in Austin (TX)',
 nan,
 '15008 Fm 812 in Del Valle (TX)',
 '13 Club Estates in Lakeway (TX)',
 '183 And Vargas in Austin (TX)',
 nan,
 nan,
 '9300 Northgate in Austin (TX)',
 '10000 Parliament House Rd in Austin (TX)',
 '7902 Dee Gabriel Collins in Austin (TX)',
 '1505 Summit St in Austin (TX)',
 nan,
 '6111 Fm2244 in Austin (TX)',
 nan,
 '7301 Singleton Bend in Austin (TX)',
 nan,
 '416 Baldridge in Austin (TX)',
 '8909 Briardale Dr in Austin (TX)',
 nan,
 '4500 Steiner in Austin (TX)',
 '15200 Fm 812 in Del Valle (TX)',
 '7201 Levander Loop in Austin (TX)',
 nan,
 '710 E Ben White Blvd in Austin (TX)',
 '2502 Citation Dr in Travis (TX)',
 '5800 Colton Rd in Austin (TX)',
 '12511 Twin Creeks Rd, Manchaca, Tx 78652 in Austin (TX)',
 '4404 E Oltorf St in Austin (TX)',
 '4821 E Riverside Dr in Austin (TX)',
 '600 W Carrie Manor in Manor (TX)',
 nan,
 '10911 Maha Loop in Austin (TX)',
 '5220 Bahan Dr in Austin (TX)',
 '5309 Cypress Ranch Blvd in Travis (TX)',
 nan,
 nan,
 '13201 Wild Turkey Drive in Travis (TX)',
 nan,
 '7208 Salt Springs - B in Austin (TX)',
 nan,
 '6700 Montana in Austin (TX)',
 '10302 Quail Valley Blvd in Austin (TX)',
 nan,
 '4511 E. Hwy 71 in Travis (TX)',
 '7700 W Parmer in Austin (TX)',
 nan,
 nan,
 nan,
 '9417 Meyrick Park Trl in Travis (TX)',
 nan,
 nan,
 nan,
 '2609 Rosewood Dr in Austin (TX)',
 nan,
 '5238 Thunder Creek in Austin (TX)',
 '5201 Ross Rd in Austin (TX)',
 '2324 Wilson St in Austin (TX)',
 '6000 Middle Fiskville Rd in Austin (TX)',
 nan,
 '10805 Topperwein Dr in Austin (TX)',
 '13021 Dessau  Rd in Austin (TX)',
 nan,
 nan,
 '1656 Rutland Drive in Austin (TX)',
 '8010 Tonopa Ln in Austin (TX)',
 nan,
 '1509 Red Fox Rd in Travis (TX)',
 '4719 Castleman in Austin (TX)',
 nan,
 '2433 S Pleasant Valley Rd in Austin (TX)',
 nan,
 nan,
 nan,
 '701 Woodward St in Austin (TX)',
 '2501 E Stassney in Austin (TX)',
 nan,
 nan,
 '7201 Levander Loop in Austin (TX)',
 '1908 Albury Cv in Austin (TX)',
 '6713 Piedras Blanco Drive in Austin (TX)',
 nan,
 nan,
 nan,
 '4601 E St Elmo Rd in Austin (TX)',
 '1901 Crazyhorse Pass in Austin (TX)',
 '10400 Bitting School in Travis (TX)',
 '3462 Laguna Dr in Travis (TX)',
 '6000 Middle Fiskville in Austin (TX)',
 '5000 East Cesar Chavez in Austin (TX)',
 '4906 Sara Dr in Austin (TX)',
 '101 W Louis Henna Blvd in Austin (TX)',
 nan,
 nan,
 '10801 Hokanson Ct in Travis (TX)',
 nan,
 '8621 Damita Jo Dr in Travis (TX)',
 '8536 Birmingham in Austin (TX)',
 '5717 Palo Blanco in Austin (TX)',
 '2406 Riddle Rd in Austin (TX)',
 nan,
 '1113 Gunter St in Austin (TX)',
 '9502 S Chisholm Trl in Austin (TX)',
 nan,
 '12341 County Line Rd in Manor (TX)',
 '11904 N Interstate 35 Frontage Rd in Austin (TX)',
 '7418 Cameron Rd in Austin (TX)',
 '2809 W Hwy 290 in Austin (TX)',
 '3220 Bridle Path in Austin (TX)',
 '14811 Chicadee in Pflugerville (TX)',
 nan,

In [45]:
df['Found_Location']=new_location
df.head()

,Animal ID,Name_intake,DateTime_intake,Found_Location,Intake_Type,IntakeCondition,Animal_Type_intake,Sex_Intake,Breed_intake,Color_intake,DateTime_outcome,Outcome_Type,Sex_upon_Outcome,fixed_changed,Age_Bucket,DateTime_length
0,A730601,No,2016-07-07 12:11:00,1109 Shady Ln in Austin (TX),Stray,Normal,Cat,Intact Male,Domestic Shorthair Mix,Blue Tabby,2016-07-08 09:00:00,Transfer,Neutered Male,1,7-12 months,0 days 20:49:00
1,A683644,Yes,2014-07-13 11:02:00,NaN,Owner Surrender,Maternity,Dog,Intact Female,Border Collie Mix,Brown/White,2014-11-06 10:06:00,Adoption,Spayed Female,1,1-6 weeks,115 days 23:04:00
2,A676515,Yes,2014-04-11 08:45:00,615 E. Wonsley in Austin (TX),Stray,Normal,Dog,Intact Male,Pit Bull Mix,White/Brown,2014-04-14 18:38:00,Return to Owner,Neutered Male,1,1-6 months,3 days 09:53:00
3,A742953,No,2017-01-31 13:30:00,NaN,Stray,Normal,Dog,Intact Male,Saluki,Sable/Cream,2017-02-04 14:17:00,Transfer,Intact Male,0,1-3 years,4 days 00:47:00
4,A679549,Yes,2014-05-22 15:43:00,124 W Anderson in Austin (TX),Stray,Normal,Cat,Intact Male,Domestic Shorthair Mix,Black/White,2014-06-16 13:54:00,Transfer,Neutered Male,1,1-6 months,24 days 22:11:00

In [46]:
df['Found_Location'].value_counts()

7201 Levander Loop in Austin (TX)            406
4434 Frontier Trl in Austin (TX)             137
124 W Anderson Ln in Austin (TX)             131
12034 Research Blvd in Austin (TX)            85
12034 Research in Austin (TX)                 85
                                            ...
10804 Pinehurst Dr in Austin (TX)              1
3226 W Slaughter Ln in Austin (TX)             1
2501 South Congress Avenue in Austin (TX)      1
8413 Elroy Rd in Travis (TX)                   1
700 San Jacinto Blvd in Austin (TX)            1
Name: Found_Location, Length: 18559, dtype: int64

In [47]:
df.isnull().sum()

Animal ID                 0
Name_intake               0
DateTime_intake           0
Found_Location        22200
Intake_Type               0
IntakeCondition           0
Animal_Type_intake        0
Sex_Intake                0
Breed_intake              0
Color_intake              0
DateTime_outcome          0
Outcome_Type              0
Sex_upon_Outcome          0
fixed_changed             0
Age_Bucket                0
DateTime_length           0
dtype: int64

In [48]:
df=df.dropna()

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 33606 entries, 0 to 76975
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Animal ID           33606 non-null  object
 1   Name_intake         33606 non-null  object
 2   DateTime_intake     33606 non-null  datetime64[ns]
 3   Found_Location      33606 non-null  object
 4   Intake_Type         33606 non-null  object
 5   IntakeCondition     33606 non-null  object
 6   Animal_Type_intake  33606 non-null  object
 7   Sex_Intake          33606 non-null  object
 8   Breed_intake        33606 non-null  object
 9   Color_intake        33606 non-null  object
 10  DateTime_outcome    33606 non-null  datetime64[ns]
 11  Outcome_Type        33606 non-null  object
 12  Sex_upon_Outcome    33606 non-null  object
 13  fixed_changed       33606 non-null  int64
 14  Age_Bucket          33606 non-null  object
 15  DateTime_length     33606 non-null  timedelta64[ns]
dtypes: datetime64[ns](2), int64(1), object(12), timedelta64[ns](1)
memory usage: 4.4+ MB

# Age Bucket column

In [50]:
df.Age_Bucket.value_counts()

1-3 years           13190
1-6 months           8679
1-6 weeks            5087
4-6 years            2692
7+ years             1767
7-12 months          1383
Less than 1 week      808
Name: Age_Bucket, dtype: int64

# Intake_Type column

In [51]:
df.Intake_Type.value_counts()

Stray                 28062
Wildlife               2548
Public Assist          1700
Owner Surrender        1285
Euthanasia Request       11
Name: Intake_Type, dtype: int64

# Breed_Intake column

In [52]:
count_breed=df.Breed_intake.value_counts()
count_breed

Domestic Shorthair Mix               12447
Pit Bull Mix                          2138
Chihuahua Shorthair Mix               1747
Labrador Retriever Mix                1519
Domestic Medium Hair Mix              1234
                                     ...
Boxer/Redbone Hound                      1
Pomeranian/Jack Russell Terrier          1
Australian Kelpie/German Shepherd        1
Chartreux Mix                            1
Shetland Sheepdog/Border Collie          1
Name: Breed_intake, Length: 1292, dtype: int64

In [53]:
for i in count_breed.index.tolist():
    print(i)

Domestic Shorthair Mix
Pit Bull Mix
Chihuahua Shorthair Mix
Labrador Retriever Mix
Domestic Medium Hair Mix
Bat Mix
Bat
Domestic Longhair Mix
German Shepherd Mix
Siamese Mix
Raccoon Mix
Australian Cattle Dog Mix
Dachshund Mix
Miniature Poodle Mix
Boxer Mix
Domestic Shorthair
Border Collie Mix
Australian Shepherd Mix
Raccoon
Catahoula Mix
Jack Russell Terrier Mix
Rat Terrier Mix
Siberian Husky Mix
Great Pyrenees Mix
Yorkshire Terrier Mix
Miniature Schnauzer Mix
Rottweiler Mix
Chihuahua Longhair Mix
Rabbit Sh Mix
Cairn Terrier Mix
Beagle Mix
Opossum Mix
Pointer Mix
Shih Tzu Mix
American Bulldog Mix
Snowshoe Mix
Queensland Heeler Mix
Plott Hound Mix
Chihuahua Shorthair/Dachshund
Opossum
Domestic Medium Hair
Pit Bull
Labrador Retriever
Staffordshire Mix
Chihuahua Shorthair
Anatol Shepherd Mix
American Staffordshire Terrier Mix
German Shepherd
Chicken Mix
Chow Chow Mix
Black Mouth Cur Mix
Miniature Pinscher Mix
Australian Kelpie Mix
Labrador Retriever/Pit Bull
Skunk Mix
German Shepherd/Labrador Retriever
Labrador Retriever/German Shepherd
Dachshund/Chihuahua Shorthair
Golden Retriever Mix
American Pit Bull Terrier Mix
Maltese Mix
Pomeranian Mix
Squirrel Mix
Lhasa Apso Mix
Pug Mix
Shih Tzu
Rottweiler
Cardigan Welsh Corgi Mix
Basset Hound Mix
Cocker Spaniel Mix
Border Terrier Mix
Doberman Pinsch Mix
Collie Smooth Mix
Toy Poodle Mix
Manx Mix
Dachshund
Mastiff Mix
Fox Mix
Blue Lacy Mix
Maine Coon Mix
Siamese
Dachshund Longhair Mix
Manchester Terrier Mix
Boston Terrier Mix
Boxer
Squirrel
Skunk
Chihuahua Shorthair/Rat Terrier
Australian Cattle Dog
Flat Coat Retriever Mix
Chinese Sharpei Mix
Pit Bull/Labrador Retriever
Siberian Husky
Dachshund Wirehair Mix
Rhod Ridgeback Mix
Labrador Retriever/Border Collie
Bull Terrier Mix
English Bulldog Mix
Russian Blue Mix
Carolina Dog Mix
Rabbit Sh
Domestic Longhair
Black/Tan Hound Mix
Dalmatian Mix
Shiba Inu Mix
Australian Cattle Dog/Labrador Retriever
Pekingese Mix
Pembroke Welsh Corgi Mix
Great Dane Mix
Wire Hair Fox Terrier Mix
Beagle
Miniature Poodle
Norfolk Terrier Mix
Chihuahua Shorthair/Jack Russell Terrier
Labrador Retriever/Australian Cattle Dog
Miniature Schnauzer
Bruss Griffon Mix
Maltese/Miniature Poodle
Weimaraner Mix
Pug
Rat Terrier/Chihuahua Shorthair
Pit Bull/Boxer
Yorkshire Terrier
Norwich Terrier Mix
Bichon Frise Mix
Redbone Hound Mix
Chihuahua Shorthair/Pug
Border Collie/Labrador Retriever
Great Pyrenees
Basenji Mix
Shetland Sheepdog Mix
Labrador Retriever/Pointer
Soft Coated Wheaten Terrier Mix
Whippet Mix
Labrador Retriever/Great Pyrenees
Harrier Mix
Alaskan Husky Mix
American Staffordshire Terrier
English Bulldog
Jack Russell Terrier
Border Collie/German Shepherd
Pomeranian
Yorkshire Terrier/Miniature Poodle
Guinea Pig Mix
Border Collie/Great Pyrenees
Boston Terrier
Cocker Spaniel
Doberman Pinsch
Miniature Schnauzer/Miniature Poodle
Akita Mix
Himalayan Mix
Labrador Retriever/Chow Chow
Ragdoll Mix
Guinea Pig
Chihuahua Shorthair/Cairn Terrier
Border Collie
Pug/Beagle
Parson Russell Terrier Mix
Dogo Argentino Mix
Standard Schnauzer Mix
Duck
Havanese Mix
German Shorthair Pointer Mix
Rat Mix
Pug/Chihuahua Shorthair
Lhasa Apso
Dachshund/Beagle
Collie Rough Mix
Yorkshire Terrier/Chihuahua Shorthair
Boxer/Pit Bull
Italian Greyhound Mix
English Pointer Mix
Smooth Fox Terrier Mix
Bullmastiff Mix
Standard Poodle Mix
Australian Cattle Dog/German Shepherd
Miniature Poodle/Miniature Schnauzer
Miniature Pinscher
Fox
Irish Terrier Mix
German Shepherd/Siberian Husky
Dove Mix
Cairn Terrier
Belgian Malinois Mix
Boxer/Labrador Retriever
Jack Russell Terrier/Chihuahua Shorthair
Pointer/Labrador Retriever
Cairn Terrier/Chihuahua Shorthair
St. Bernard Rough Coat Mix
Dutch Shepherd Mix
Catahoula/Plott Hound
Australian Shepherd
Great Dane
Golden Retriever
Pit Bull/Catahoula
American Eskimo Mix
Labrador Retriever/Boxer
Chicken
Treeing Walker Coonhound Mix
Jack Russell Terrier/Australian Cattle Dog
Papillon Mix
Pigeon Mix
Bulldog Mix
Lizard Mix
Persian Mix
Vizsla Mix
West Highland Mix
Feist Mix
Rat Terrier
Labrador Retriever/Golden Retriever
American Shorthair Mix
Dachshund/Rat Terrier
Chesa Bay Retr Mix
Chihuahua Shorthair/Yorkshire Terrier
Beagle/Dachshund
Angora Mix
Patterdale Terr Mix
Greyhound
Labrador Retriever/Australian Shepherd
Chinese Sharpei/Labrador Retriever
Plott Hound/Labrador Retriever
Basset Hound
Bantam Mix
Labrador Retriever/Beagle
Finnish Spitz Mix
Chinese Crested Mix
St. Bernard Smooth Coat Mix
Chihuahua Shorthair/Cardigan Welsh Corgi
Australian Shepherd/Anatol Shepherd
Pekingese
Siberian Husky/German Shepherd
Bluetick Hound Mix
Chihuahua Shorthair/Beagle
Turtle Mix
Bloodhound Mix
Labrador Retriever/Rottweiler
Bernese Mountain Dog Mix
Chihuahua Shorthair/Miniature Pinscher
Glen Of Imaal Mix
Silky Terrier Mix
German Shepherd/Rottweiler
Rottweiler/Labrador Retriever
Samoyed Mix
Labrador Retriever/Chinese Sharpei
Rex Mix
English Coonhound Mix
German Shepherd/Mastiff
Miniature Poodle/Maltese
Catahoula
Labrador Retriever/Anatol Shepherd
French Bulldog Mix
Flat Coat Retriever/Papillon
Havana Mix
Maltese
Australian Cattle Dog/Pit Bull
Swedish Vallhund Mix
Hamster
Ferret
Catahoula/Pit Bull
Brittany Mix
Bombay Mix
Cardigan Welsh Corgi/Australian Cattle Dog
Dachshund/Labrador Retriever
Blue Lacy/American Bulldog
Tibetan Spaniel Mix
Dachshund Wirehair/Border Terrier
Shih Tzu/Miniature Poodle
Toy Poodle
Catahoula/Labrador Retriever
Cockatiel Mix
Mexican Hairless Mix
Scottish Terrier Mix
Staffordshire
Alaskan Malamute Mix
Great Pyrenees/Labrador Retriever
Ferret Mix
New Zealand Wht Mix
Cavalier Span Mix
Pomeranian/Chihuahua Longhair
Chow Chow
Toy Fox Terrier Mix
Tarantula
Airedale Terrier Mix
Lionhead Mix
Rhod Ridgeback/Labrador Retriever
Californian Mix
Rat
Weimaraner
English Shepherd Mix
Black Mouth Cur
Duck Mix
Border Collie/Australian Cattle Dog
German Shepherd/Australian Cattle Dog
British Shorthair Mix
Golden Retriever/Labrador Retriever
Dachshund Longhair
Anatol Shepherd/Labrador Retriever
Snake
Anatol Shepherd/Great Pyrenees
Dachshund Wirehair/Chihuahua Shorthair
English Spot Mix
Tibetan Terrier Mix
Lhasa Apso/Miniature Poodle
Carolina Dog/Chihuahua Shorthair
Greyhound Mix
Snake Mix
Australian Shepherd/Labrador Retriever
Cold Water
German Shepherd/Chow Chow
Beauceron Mix
Jack Russell Terrier/Dachshund
Shetland Sheepdog
Great Pyrenees/Anatol Shepherd
Coyote Mix
Chow Chow/German Shepherd
Great Pyrenees/Border Collie
Australian Shepherd/Chihuahua Shorthair
Pointer/Boxer
Snowshoe
Cardigan Welsh Corgi/Chihuahua Shorthair
Pit Bull/Chinese Sharpei
Parakeet Mix
Labrador Retriever/Basset Hound
Pit Bull/Pointer
Cavalier Span
Labrador Retriever/Plott Hound
Turkey Mix
Beagle/Labrador Retriever
Lop-English Mix
Chihuahua Longhair
Irish Wolfhound Mix
Great Dane/Labrador Retriever
Black Mouth Cur/Catahoula
Labrador Retriever/Black/Tan Hound
Labrador Retriever/Great Dane
Basset Hound/Pit Bull
Harrier
Yorkshire Terrier/Miniature Schnauzer
American Bulldog
Australian Cattle Dog/Pointer
Parson Russell Terrier
Basset Hound/Beagle
Boxer/Beagle
Pharaoh Hound Mix
Miniature Pinscher/Pug
Wirehaired Pointing Griffon Mix
Pbgv Mix
Golden Retriever/Chow Chow
Jack Russell Terrier/Rat Terrier
German Shepherd/Cardigan Welsh Corgi
Chinese Sharpei
Siberian Husky/Border Collie
Presa Canario Mix
Picardy Sheepdog Mix
Border Collie/Chow Chow
Miniature Poodle/Cocker Spaniel
Black/Tan Hound
Grackle Mix
German Shepherd/Border Collie
Bengal Mix
Schnauzer Giant Mix
Chihuahua Shorthair/Italian Greyhound
Leonberger Mix
Armadillo Mix
English Springer Spaniel Mix
Pit Bull/Plott Hound
German Shepherd/Alaskan Malamute
Redbone Hound/Labrador Retriever
Jack Russell Terrier/Labrador Retriever
Chihuahua Shorthair/Dachshund Wirehair
Field Spaniel Mix
German Shepherd/Boxer
Miniature Pinscher/Chihuahua Shorthair
Chihuahua Shorthair/Boston Terrier
Border Terrier/Chihuahua Shorthair
Chihuahua Longhair/Cairn Terrier
Pit Bull/Australian Cattle Dog
Australian Terrier Mix
Tonkinese Mix
Pointer/American Pit Bull Terrier
Hamster Mix
German Shepherd/Chinese Sharpei
Australian Kelpie
American Foxhound Mix
Grackle
Catahoula/Australian Cattle Dog
Rhod Ridgeback
Beagle/Chihuahua Shorthair
Cocker Spaniel/Miniature Poodle
Treeing Cur Mix
Basset Hound/Chinese Sharpei
German Shepherd/Great Pyrenees
Canaan Dog Mix
Old English Bulldog Mix
Australian Cattle Dog/Australian Shepherd
Yorkshire Terrier/Cairn Terrier
Keeshond Mix
Pointer/Pit Bull
Miniature Poodle/Bichon Frise
Akita
Belgian Sheepdog Mix
Himalayan
American Pit Bull Terrier
Dove
Japanese Bobtail Mix
Collie Smooth/Labrador Retriever
Whippet/Dachshund
Californian
German Shepherd/Collie Rough
Pit Bull/Bulldog
Rottweiler/Chow Chow
Golden Retriever/Border Collie
Mastiff
Labrador Retriever/Flat Coat Retriever
Australian Cattle Dog/Bull Terrier
Border Collie/Catahoula
Pointer/Catahoula
Dachshund/Pit Bull
Queensland Heeler/Pit Bull
Lionhead
Queensland Heeler
Balinese Mix
Devon Rex Mix
German Shepherd/Black/Tan Hound
Bullmastiff
Rat Terrier/Miniature Poodle
Australian Cattle Dog/Plott Hound
Catahoula/German Shepherd
Norfolk Terrier/Chihuahua Shorthair
Chow Chow/Labrador Retriever
Miniature Poodle/Lhasa Apso
Miniature Schnauzer/Yorkshire Terrier
Labrador Retriever/Siberian Husky
Landseer Mix
Tortoise Mix
Jack Russell Terrier/Shih Tzu
Cardigan Welsh Corgi/German Shepherd
American Staffordshire Terrier/American Bulldog
Pit Bull/Mastiff
Chihuahua Longhair/Maltese
Pig Mix
Cairn Terrier/Yorkshire Terrier
Labrador Retriever/Catahoula
Dachshund/Bloodhound
Bull Terrier
Exotic Shorthair Mix
Sparrow Mix
Pit Bull/Weimaraner
Persian
German Shepherd/Australian Shepherd
Pit Bull/German Shepherd
Rat Terrier/Beagle
Manchester Terrier/Jack Russell Terrier
Bloodhound
Quaker Mix
Australian Shepherd/Cardigan Welsh Corgi
Boerboel Mix
Pointer/Australian Cattle Dog
Miniature Poodle/Chihuahua Shorthair
Manx/Domestic Shorthair
Chihuahua Shorthair/Pembroke Welsh Corgi
Chihuahua Longhair/Jack Russell Terrier
Welsh Terrier Mix
Pigeon
Affenpinscher Mix
Basenji/Chihuahua Shorthair
Cairn Terrier/Miniature Schnauzer
Maine Coon
Standard Poodle/Labrador Retriever
Anatol Shepherd/Border Collie
Border Collie/Boxer
Jack Russell Terrier/Beagle
Boston Terrier/Chihuahua Shorthair
Coyote
Chihuahua Longhair/Dachshund
Black Mouth Cur/German Shepherd
Newfoundland/Labrador Retriever
Boxer/American Staffordshire Terrier
Pointer
Doberman Pinsch/Labrador Retriever
Rottweiler/German Shepherd
Australian Shepherd/Border Collie
Great Pyrenees/Catahoula
Bearded Collie Mix
Schipperke Mix
Beagle/Rat Terrier
German Shepherd/Catahoula
German Wirehaired Pointer Mix
Wire Hair Fox Terrier/Chihuahua Shorthair
Collie Smooth/German Shepherd
Boykin Span Mix
Labrador Retriever/Collie Rough
Nova Scotia Duck Tolling Retriever Mix
German Shepherd/Golden Retriever
Catahoula/Beagle
Australian Cattle Dog/Chow Chow
Dachshund Wirehair
Jack Russell Terrier/Miniature Poodle
West Highland
German Shepherd/Alaskan Husky
Belgian Malinois
Soft Coated Wheaten Terrier
Border Collie/Parson Russell Terrier
Rottweiler/Australian Cattle Dog
Abyssinian Mix
Great Pyrenees/Australian Shepherd
Yorkshire Terrier/Chihuahua Longhair
Shiba Inu
Australian Cattle Dog/Pembroke Welsh Corgi
Irish Terrier/Labrador Retriever
American Mix
Bull Terrier Miniature Mix
Siberian Husky/Labrador Retriever
English Foxhound Mix
Basenji/Australian Cattle Dog
Black Mouth Cur/Boxer
Border Collie/Basenji
Japanese Chin Mix
American Eskimo
German Shepherd/Bull Terrier
Heron Mix
Dachshund/English Foxhound
Border Collie/Dachshund
Carolina Dog/Australian Cattle Dog
Staffordshire/Labrador Retriever
Queensland Heeler/Pointer
English Bulldog/Boxer
Rat Terrier/Dachshund
Domestic Shorthair/Siamese
Doberman Pinsch/Australian Cattle Dog
Cardigan Welsh Corgi
Cane Corso Mix
Chow Chow/Pit Bull
Beagle/German Shepherd
Labrador Retriever/Vizsla
Turkish Van Mix
Chihuahua Longhair/Pomeranian
Cymric Mix
Miniature Schnauzer/Cairn Terrier
Pharaoh Hound
Cardigan Welsh Corgi/Beagle
Pekingese/Jack Russell Terrier
Pbgv
Parrot
Maltese/Toy Poodle
Jack Russell Terrier/Border Collie
Papillon
Labrador Retriever/Newfoundland
Cocker Spaniel/Chihuahua Shorthair
Pit Bull/Dalmatian
Chihuahua Shorthair/Smooth Fox Terrier
Australian Shepherd/Alaskan Malamute
Maltese/Jack Russell Terrier
Manx/Domestic Longhair
Blue Lacy/Weimaraner
Yorkshire Terrier/Lhasa Apso
Chihuahua Shorthair/Australian Cattle Dog
Labrador Retriever/Staffordshire
Oriental Sh Mix
German Shepherd/Pit Bull
Pointer/Jack Russell Terrier
Bichon Frise
German Shepherd/Collie Smooth
Turtle
English Foxhound
Parakeet
German Shepherd/Doberman Pinsch
Standard Poodle
Cane Corso
Beagle/Pug
Javanese Mix
Welsh Springer Spaniel
Australian Cattle Dog/Beagle
Border Terrier
Collie Rough/German Shepherd
Old English Sheepdog
Rabbit Lh Mix
Australian Cattle Dog/Catahoula
American Bulldog/Mastiff
Australian Shepherd/Australian Cattle Dog
Border Collie/Pembroke Welsh Corgi
Finnish Spitz
Labrador Retriever/Dachshund
Black/Tan Hound/Labrador Retriever
Bernese Mountain Dog
Old English Bulldog
Lop-Holland Mix
Labrador Retriever/Collie Smooth
Chihuahua Shorthair/Manchester Terrier
Great Pyrenees/Golden Retriever
Boxer/Chinese Sharpei
Dachshund/Miniature Poodle
Alaskan Malamute
Bluebird Mix
Newfoundland Mix
Boston Terrier/Pit Bull
Pit Bull/Basset Hound
Skye Terrier Mix
Anatol Shepherd/Australian Cattle Dog
Russian Blue
Pit Bull/Boston Terrier
Vizsla/Labrador Retriever
Schipperke/Chihuahua Shorthair
Dalmatian/Pit Bull
Lhasa Apso/Cairn Terrier
Bengal
Shih Tzu/Yorkshire Terrier
Labrador Retriever/German Shorthair Pointer
Chinese Sharpei/Chow Chow
Chihuahua Longhair/Dachshund Longhair
Australian Cattle Dog/Border Collie
Queensland Heeler/Chihuahua Shorthair
Neapolitan Mastiff Mix
Cottontail Mix
Yorkshire Terrier/Norfolk Terrier
Armadillo
Rhode Island Mix
German Pinscher Mix
Dachshund/Pug
Anatol Shepherd
Rat Terrier/Boston Terrier
Ibizan Hound Mix
Cairn Terrier/Miniature Poodle
Plott Hound
Vizsla
Australian Cattle Dog/Bloodhound
Jack Russell Terrier/Italian Greyhound
Doberman Pinsch/German Shepherd
Plott Hound/Pit Bull
Cockatoo
Australian Cattle Dog/Basenji
French Bulldog
American Bulldog/Pit Bull
Labrador Retriever/Mastiff
Labrador Retriever/Doberman Pinsch
Australian Cattle Dog/German Shorthair Pointer
French Bulldog/Chihuahua Shorthair
American Bulldog/Boxer
Bull Terrier Miniature
Beagle/Boxer
Border Collie/Pointer
Border Collie/Akita
Conure
Miniature Poodle/Dachshund
Labrador Retriever/Labrador Retriever
Dogue De Bordeaux Mix
Bedlington Terr Mix
Manchester Terrier/Chihuahua Shorthair
Norwegian Forest Cat Mix
Collie Rough/Australian Shepherd
Basset Hound/Labrador Retriever
Carolina Dog
Alaskan Husky
Maltese/Shih Tzu
Maltese/Yorkshire Terrier
Chihuahua Longhair/Cardigan Welsh Corgi
Collie Rough
Black Mouth Cur/Blue Lacy
Boxer/Australian Cattle Dog
Anatol Shepherd/Catahoula
Australian Cattle Dog/Queensland Heeler
Shih Tzu/Toy Poodle
Labrador Retriever/Jack Russell Terrier
Dachshund/Jack Russell Terrier
Cairn Terrier/Chihuahua Longhair
German Shepherd/Pembroke Welsh Corgi
Hawk
Australian Cattle Dog/Cardigan Welsh Corgi
Podengo Pequeno Mix
Great Pyrenees/Australian Cattle Dog
American Pit Bull Terrier/Catahoula
Chihuahua Shorthair/Miniature Schnauzer
Australian Kelpie/Beagle
Mastiff/Labrador Retriever
Collie Smooth
Dachshund/Harrier
Pit Bull/Chihuahua Shorthair
Catahoula/Alaskan Husky
Australian Shepherd/Brittany
Lhasa Apso/Cocker Spaniel
Doberman Pinsch/Pit Bull
Rat Terrier/Chihuahua Longhair
American Staffordshire Terrier/Pit Bull
Beagle/Australian Cattle Dog
Pembroke Welsh Corgi/Anatol Shepherd
Manx
Border Terrier/Pug
Australian Shepherd/Rottweiler
Pointer/Border Collie
Chihuahua Longhair/Cavalier Span
Harrier/Catahoula
Blue Lacy/Black Mouth Cur
Munchkin Longhair Mix
Guinea Mix
Miniature Pinscher/Smooth Fox Terrier
Border Collie/Pit Bull
Chihuahua Longhair/Yorkshire Terrier
Beagle/Boston Terrier
Siberian Husky/Australian Cattle Dog
Dachshund/Yorkshire Terrier
Vizsla/Rhod Ridgeback
Rhod Ridgeback/Boxer
Manx/Siamese
Maltese/Lhasa Apso
Border Collie/Standard Schnauzer
Akita/Border Collie
German Shorthair Pointer
Alaskan Husky/German Shepherd
Peafowl
Jack Russell Terrier/American Staffordshire Terrier
Plott Hound/Black/Tan Hound
Labrador Retriever/Dalmatian
Standard Schnauzer
Border Collie/Beagle
Australian Cattle Dog/Alaskan Husky
Belgian Malinois/Australian Shepherd
Papillon/Pomeranian
Yorkshire Terrier/Toy Poodle
Border Collie/Queensland Heeler
Pointer/Collie Smooth
Boykin Span/Dachshund
Miniature Poodle/Italian Greyhound
Blue Lacy/Collie Smooth
Yorkshire Terrier/Shih Tzu
Maltese/Border Terrier
Dutch Shepherd/Boxer
Border Terrier/Soft Coated Wheaten Terrier
Heron
Boxer/English Bulldog
Dachshund/Blue Lacy
Jack Russell Terrier/Chihuahua Longhair
Standard Schnauzer/Toy Poodle
Collie Rough/Labrador Retriever
Golden Retriever/Standard Poodle
Treeing Walker Coonhound/Australian Cattle Dog
Lhasa Apso/Miniature Schnauzer
Blue Lacy/Pit Bull
Chihuahua Longhair/Rat Terrier
Dachshund/German Pinscher
American Foxhound/Labrador Retriever
Jersey Wooly Mix
Miniature Schnauzer/Shih Tzu
Shih Tzu/Norfolk Terrier
Labrador Retriever/American Foxhound
Domestic Shorthair/Manx
Chihuahua Shorthair/Labrador Retriever
Chihuahua Shorthair/Toy Fox Terrier
Collie Rough/Anatol Shepherd
Chihuahua Shorthair/Cirneco
Labrador Retriever/Blue Lacy
Great Dane/Boxer
Great Pyrenees/Collie Rough
German Wirehaired Pointer
Quaker
Havana Brown Mix
Miniature Poodle/Pomeranian
Leonberger/German Shepherd
Chesa Bay Retr/Labrador Retriever
Chihuahua Shorthair/Miniature Poodle
Dachshund/Miniature Pinscher
Rhod Ridgeback/Pit Bull
Snowshoe/Ragdoll
Dachshund Longhair/Cocker Spaniel
Manchester Terrier/Beagle
Pekingese/Tibetan Terrier
Blue Lacy/Pointer
Boxer/Neapolitan Mastiff
Lakeland Terrier Mix
Plott Hound/Whippet
Basset Hound/Australian Cattle Dog
Siamese/Angora
Pit Bull/English Bulldog
Chihuahua Longhair/Papillon
English Coonhound/Australian Cattle Dog
Australian Shepherd/Cocker Spaniel
Blue Lacy
Plott Hound/German Shepherd
Airedale Terrier/Miniature Schnauzer
Anatol Shepherd/German Shepherd
Chow Chow/Australian Kelpie
Bull Terrier/Australian Kelpie
American Staffordshire Terrier/Boxer
Greater Swiss Mountain Dog Mix
Maltese/Dalmatian
Beagle/Parson Russell Terrier
Dachshund/Pomeranian
Dutch
Australian Cattle Dog/Siberian Husky
Dachshund Wirehair/Chihuahua Longhair
Skye Terrier/Miniature Poodle
American Pit Bull Terrier/Pit Bull
Carolina Dog/Border Collie
Mastiff/Rottweiler
Rat Terrier/English Pointer
Basset Hound/Border Collie
Australian Shepherd/Collie Rough
English Springer Spaniel
Staffordshire/Beagle
Australian Cattle Dog/Boxer
Shih Tzu/Australian Shepherd
Shetland Sheepdog/Brittany
Shih Tzu/Pekingese
Shih Tzu/Cocker Spaniel
Pit Bull/Rottweiler
Rabbit Lh
Feist/Beagle
Queensland Heeler/Australian Cattle Dog
Chow Chow/Irish Setter
Lop-Mini
Dachshund Longhair/Cairn Terrier
Queensland Heeler/Dachshund
Lhasa Apso/Toy Poodle
Burmese
Irish Wolfhound/Great Pyrenees
Catahoula/Mastiff
Shih Tzu/Maltese
Siberian Husky/Cardigan Welsh Corgi
Boxer/Staffordshire
Cavalier Span/Jack Russell Terrier
Neapolitan Mastiff/Pit Bull
Chow Chow/Golden Retriever
Lizard
Norfolk Terrier/Dachshund Wirehair
Great Dane/Australian Cattle Dog
Great Pyrenees/German Shepherd
Queensland Heeler/Parson Russell Terrier
Jack Russell Terrier/Dachshund Wirehair
Dutch Mix
Lovebird Mix
Beagle/Australian Kelpie
Jack Russell Terrier/Basenji
English Setter Mix
Norfolk Terrier/Cairn Terrier
Chihuahua Shorthair/German Shepherd
Pug/Pomeranian
Labrador Retriever/Alaskan Malamute
Dachshund Longhair/Cardigan Welsh Corgi
Lhasa Apso/Shih Tzu
Brittany/Collie Rough
Whippet/Whippet
Chihuahua Shorthair/Mexican Hairless
Flat Coat Retriever/German Shepherd
Miniature Schnauzer/Scottish Terrier
Bruss Griffon/Yorkshire Terrier
Staffordshire/Blue Lacy
Old English Sheepdog Mix
Boston Terrier/Pug
Basset Hound/Dachshund
Australian Cattle Dog/English Coonhound
Dalmatian
Patterdale Terr/Chihuahua Shorthair
Pug/Border Terrier
Border Terrier/Yorkshire Terrier
Gordon Setter Mix
Toy Poodle/Dachshund
Norwich Terrier
Great Dane/Boerboel

In [54]:
# Find Mix breeds
new_breed=[]
for i in df['Breed_intake']:
    if 'Mix' in i:
        i='Mix'
    elif "/" in i:
        i="Mix"
    elif 'Chihuahua' in i:
        i = 'Chihuahua'
    elif 'Retriever' in i or i=='Chesa Bay Retr':
        i = 'Retriever Breeds'
    elif 'Bull' in i or 'Staffordshire' in i or i=='Chinese Sharpei' or i=='Dogo Argentino' or i=='Boxer':
        i = 'Bully Breeds'
    elif 'Terrier' in i:
        i= 'Terrier Breeds'
    elif i=='Bat' or i=='Raccoon' or i=='Opossum' or i=='Duck' or i=='Fox' or i=='Grackle' or i=='Hawk' or i=='Coyote' or i=='Pigeon' or i=='Dove' or i=='Armadillo' or i=='Owl' or i=='Skunk' or i=='Squirrel' or i=='Mockingbird' or i=='Heron' or i=='Sparrow':
        i = 'Wildlife'
    elif i=='German Shepherd' or i=='Belgian Malinois':
        i = 'German Shepherd'
    elif 'Pointer' in i or 'Span' in i or i=='Vizsla' or i=='Brittany' or i=='Shiba Inu' or i=='Dalmatian' or i=='Standard Poodle' or i=='Carolina Dog' or i=='Weimaraner':
        i = 'Sporting Breeds'
    elif 'hound' in i or 'Hound' in i or i=='Beagle' or i=='Saluki' or 'Coon' in i or i=='Catahoula' or i=='Black Mouth Cur' or i=='Harrier' or i=='Blue Lacy' or i=='Treeing Tennesse Brindle' or i=='Whippet':
        i = 'Hound Breeds'
    elif 'Husky' in i or 'Malamute' in i or 'Eskimo' in i or i=='Finnish Spitz' or i=='Samoyed' or i=='Keeshond' or i=='Jindo':
        i = 'Husky Breeds'
    elif i=='Shih Tzu' or i=='Miniature Poodle' or i=='Miniature Schnauzer' or i=='Maltese' or i=='Pomeranian' or i=='Lhasa Apso' or i=='Toy Poodle' or i=='Pekingese' or i=='Bichon Frise' or i=='Cavalier Span' or i=='West Highland' or i=='Papillon' or i=='Havanese' or i=='Japanese Chin' or i=='Dandie Dinmont' or i=='Bruss Griffon' or i=='Coton De Tulear' or 'Dachshund' in i or i=='French Bulldog' or i=='Pug' or i=='Miniature Pinscher' or i=='Pbgv':
        i = 'Toy Breeds'
    elif 'Australian' in i or 'Collie' in i or 'Heeler' in i or 'Sheepdog' in i or i=='English Shepherd' or i=='Dutch Shepherd' or 'Corgi' in i or i=='Beauceron' or i=='Hovawart':
        i = 'Herding Breeds'
    elif i=='Chinese Sharpei' or i=='Chow Chow' or i=='Standard Schnauzer' or i=='Basenji' or i=='Rottweiler' or i=='Doberman Pinsch':
        i = 'Working Breeds'
    elif i=='Great Pyrenees' or i=='Great Dane' or i=='Anatol Shepherd' or i=='Cane Corso' or i=='Rhod Ridgeback' or i=='Akita' or i=='Mastiff' or i=='Presa Canario' or 'Bernese' in i or i=='Burmese' or 'Bernard' in i or i=='Leonberger' or i=='Greater Swiss Mountain Dog' or i=='Boerboel'or i=='Landseer':
        i = 'X Large Breeds'
    elif i=='Domestic Shorthair':
        i = 'Domestic Shorthair'
    elif i=='Domestic Medium Hair':
        i = 'Domestic Medium Hair'
    elif i=='Persian' or i=='Siamese' or i=='Domestic Longhair' or i=='Persian' or i=='Himalayan' or i=='Russian Blue' or i=='Bengal' or i=='Devon Rex' or i=='Sphynx' or i=='British Shorthair' or i=='Manx':
        i = 'Other Cat'
    else:
        i='Other'
    new_breed.append(i)
new_breed

['Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Wildlife',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Hound Breeds',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Bully Breeds',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Retriever Breeds',
 'Wildlife',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Domestic Medium Hair',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Other Cat',
 'Terrier Breeds',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Wildlife',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Wildlife',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Wildlife',
 'Mix',
 'Mix',
 'Mix',
 'Retriever Breeds',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Wildlife',
 'Hound Breeds',
 'Mix',
 'Mix',
 'Terrier Breeds',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Bully Breeds',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'X Large Breeds',
 'Mix',
 'Mix',
 'Wildlife',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Wildlife',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Domestic Medium Hair',
 'Mix',
 'Mix',
 'Hound Breeds',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Herding Breeds',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Bully Breeds',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Toy Breeds',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Wildlife',
 'Mix',
 'Mix',
 'Mix',
 'X Large Breeds',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Other Cat',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Chihuahua',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Sporting Breeds',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Retriever Breeds',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Wildlife',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Other',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Terrier Breeds',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Domestic Medium Hair',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Toy Breeds',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Other',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Wildlife',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Terrier Breeds',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Wildlife',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Bully Breeds',
 'Mix',
 'Mix',
 'X Large Breeds',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Bully Breeds',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Sporting Breeds',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Other Cat',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Wildlife',
 'Mix',
 'Mix',
 'Domestic Medium Hair',
 'Sporting Breeds',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Bully Breeds',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Chihuahua',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Wildlife',
 'Wildlife',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Domestic Shorthair',
 'Mix',
 'Mix',
 'Wildlife',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Hound Breeds',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Wildlife',
 'Mix',
 'Mix',
 'Mix',
 'German Shepherd',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Terrier Breeds',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Wildlife',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Wildlife',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Wildlife',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Bully Breeds',
 'Wildlife',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Wildlife',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Bully Breeds',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Wildlife',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Wildlife',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Wildlife',
 'Mix',
 'Wildlife',
 'Mix',
 'Mix',
 'Mix',
 'Wildlife',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Bully Breeds',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'German Shepherd',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 'Mix',
 ...]

In [55]:
df["new_breed"]=new_breed

In [56]:
breed_counts=df['new_breed'].value_counts()
breed_counts

Mix                     31109
Wildlife                 1029
Toy Breeds                211
Domestic Shorthair        191
Bully Breeds              166
Other                     108
Retriever Breeds           88
Domestic Medium Hair       81
Chihuahua                  80
Herding Breeds             73
German Shepherd            72
Terrier Breeds             72
Other Cat                  69
Hound Breeds               67
Working Breeds             65
X Large Breeds             46
Sporting Breeds            42
Husky Breeds               37
Name: new_breed, dtype: int64

In [57]:
replace_breed=breed_counts.loc[breed_counts<100].index.tolist()
for i in replace_breed:
    df.new_breed = df.new_breed.replace(i,"Other")

df.new_breed.value_counts()

Mix                   31109
Wildlife               1029
Other                   900
Toy Breeds              211
Domestic Shorthair      191
Bully Breeds            166
Name: new_breed, dtype: int64

In [58]:
# drop and rename
df=df.drop(columns=['Breed_intake'])
df=df.rename(columns={"new_breed": "Breed_Type"})
df.head()

,Animal ID,Name_intake,DateTime_intake,Found_Location,Intake_Type,IntakeCondition,Animal_Type_intake,Sex_Intake,Color_intake,DateTime_outcome,Outcome_Type,Sex_upon_Outcome,fixed_changed,Age_Bucket,DateTime_length,Breed_Type
0,A730601,No,2016-07-07 12:11:00,1109 Shady Ln in Austin (TX),Stray,Normal,Cat,Intact Male,Blue Tabby,2016-07-08 09:00:00,Transfer,Neutered Male,1,7-12 months,0 days 20:49:00,Mix
2,A676515,Yes,2014-04-11 08:45:00,615 E. Wonsley in Austin (TX),Stray,Normal,Dog,Intact Male,White/Brown,2014-04-14 18:38:00,Return to Owner,Neutered Male,1,1-6 months,3 days 09:53:00,Mix
4,A679549,Yes,2014-05-22 15:43:00,124 W Anderson in Austin (TX),Stray,Normal,Cat,Intact Male,Black/White,2014-06-16 13:54:00,Transfer,Neutered Male,1,1-6 months,24 days 22:11:00,Mix
5,A683798,Yes,2016-07-21 12:16:00,3118 Windsor Rd in Austin (TX),Stray,Normal,Cat,Spayed Female,White/Black,2016-10-18 10:55:00,Adoption,Spayed Female,0,1-3 years,88 days 22:39:00,Mix
9,A683656,No,2014-07-13 13:20:00,8238 Research Blvd in Austin (TX),Stray,Normal,Cat,Intact Male,Lynx Point,2014-07-17 16:57:00,Adoption,Neutered Male,1,1-6 months,4 days 03:37:00,Mix

### option: divide breed type by mix and purebred?

# Color_intake column

In [59]:
color_counts=df['Color_intake'].value_counts()
color_counts

Black/White            3315
Black                  3044
Brown Tabby            2372
Brown                  1873
Brown Tabby/White      1222
                       ...
Lilac Point/Cream         1
Tan/Red Tick              1
Tricolor/Blue Tick        1
White/Pink                1
Black Brindle/Black       1
Name: Color_intake, Length: 402, dtype: int64

In [60]:
for i in color_counts.index:
    print(i)

Black/White
Black
Brown Tabby
Brown
Brown Tabby/White
Orange Tabby
White
Blue/White
White/Black
Brown/White
Tan/White
Tortie
Blue
Black/Tan
Calico
Tan
Brown/Black
Tricolor
Black/Brown
Blue Tabby
Orange Tabby/White
White/Brown
Torbie
Brown Brindle/White
Red
White/Tan
Red/White
Blue Tabby/White
Cream Tabby
Brown Brindle
Gray
Lynx Point
Gray/Black
Tan/Black
Seal Point
Yellow
Chocolate/White
Sable
Cream
White/Blue
Buff
Black/Gray
Chocolate
White/Brown Tabby
Gray/White
Cream Tabby/White
Black Tabby
White/Brown Brindle
Flame Point
Fawn/White
White/Gray
Torbie/White
Sable/White
Brown/Tan
Blue Merle
White/Red
Fawn
Red/Black
White/Orange Tabby
Chocolate/Tan
Gray Tabby
Black Smoke
Black Brindle/White
Yellow/White
Buff/White
White/Tricolor
Lilac Point
Gold
Cream/White
Blue Merle/White
Black Tabby/White
Tortie Point
Orange/White
White/Orange
White/Chocolate
Black/Tricolor
White/Cream
Orange
Tan/Brown
Blue Point
Black/Brown Brindle
Blue/Tan
Red/Tan
Silver Tabby
Calico/White
Calico Point
Black/Red
Tortie/White
Brown Merle
Brown Merle/White
White/Buff
Red Tick
Chocolate Point
White/Blue Tabby
Brown Tabby/Black
Blue Merle/Tan
Gray Tabby/White
Black Brindle
Fawn/Black
Blue Tick
Lynx Point/White
Pink
Seal Point/White
Brown/Gray
Red Merle
Black/Black
Black/Cream
Red Merle/White
Tricolor/White
Apricot
Black Smoke/White
Brown/Red
Silver
Brown Brindle/Black
Yellow Brindle/White
Blue Cream
White/White
Red/Brown
Blue Tiger/White
Sable/Tan
Tan/Gray
Silver/Tan
Silver Tabby/White
Tricolor/Black
Blue Tick/Black
Sable/Black
Yellow/Black
Green
Gray/Brown
Tan/Silver
Tan/Cream
Yellow Brindle
White/Black Brindle
White/Liver
Blue Tick/Tan
Red/Cream
Cream/Black
Black/Orange
Liver/White
Gold/White
Cream/Tan
White/Blue Merle
Gray/Tan
White/Cream Tabby
Black/Chocolate
Buff/Tan
Silver Lynx Point
Calico/Black
Black/Blue Merle
Brown/Tricolor
Brown Tiger
Gray/Red
Tricolor/Brown
Sable/Brown
Agouti
Blue Smoke
Gray/Pink
Blue Merle/Black
White/Red Merle
Tan/Tan
Red Tick/White
Black/Silver
Black/Black Brindle
Brown/Cream
Apricot/White
Silver/Black
Black/Blue
Chocolate Point/White
Chocolate/Brown
Blue/Black
White/Brown Merle
Brown/Brown
Buff/Black
Black/Buff
Black Brindle/Brown
Gray/Orange
Blue Merle/Brown
White/Red Tick
Tortie/Blue Cream
Fawn/Blue
White/Black Tabby
Red/Gray
Brown Tabby/Brown Tabby
Brown Tabby/Brown
Liver/Tan
Black/Yellow
Fawn/Tan
Fawn/Brown
Green/Blue
Black/Blue Tick
Blue Tick/White
Brown Brindle/Tan
Blue/Brown
Blue/Tricolor
Calico/Blue Cream
Cream/Red
Blue Tiger
Chocolate/Tricolor
White/Chocolate Point
White/Silver
Blue Tabby/Cream
Brown/Silver
Calico/Brown Tabby
Blue/Brown Brindle
Blue Point/White
Brown Tabby/Tortie
Brown/Chocolate
Gray/Silver
Brown/Yellow
White/Calico
Lilac Point/White
Green/Yellow
Cream/Brown
Tan/Tricolor
Tan/Buff
Brown Tabby/Orange
White/Yellow
Gold/Black
Orange/Tan
Brown/Buff
Black/Gray Tabby
Cream/Seal Point
Liver Tick
Cream/Orange
Tortie/Orange
Brown Brindle/Brown
White/Yellow Brindle
Gray/Blue
Sable/Red
Silver/White
Liver
White/Gray Tabby
Black/Pink
Blue Tick/Red
Red Tick/Tan
Black/Brown Tabby
Gray Tabby/Black
Sable/Cream
Blue/Blue
Yellow/Orange
Tortie/Calico
White/Blue Tick
Blue Merle/Blue Merle
Silver/Chocolate
Calico/Tricolor
Red/Silver
Seal Point/Brown
Tricolor/Brown Merle
Yellow/Cream
Calico Point/White
Torbie/Brown Tabby
Orange Tabby/Orange
Brown Tiger/White
Green/Brown
Silver/Brown
Black/Black Smoke
Tricolor/Blue
Red Tick/Red
Orange Tabby/Cream
Blue/Tortie
Red/Buff
Brown/Red Tick
Tortie/Blue
Apricot/Brown
Chocolate/Cream
Chocolate/Brown Tabby
Brown/Green
Tortie/Black
Blue Cream/White
Calico/Brown
Buff/Gray
Tortie Point/White
Fawn/Gray
Gray/Tortie
White/Apricot
Gray/Yellow
Tan/Yellow
White/Black Smoke
Orange Tiger
Black Brindle/Blue Tick
Brown/Blue
Torbie/Calico
Chocolate/Yellow
Brown/Blue Merle
Brown/Brown Brindle
Blue Cream/Blue Tiger
Buff/Red
Brown Tabby/Blue
White/Lynx Point
Cream Tabby/Cream Tabby
Red Tick/Brown Merle
Lynx Point/Tan
Chocolate/Black
Brown Tabby/Gray Tabby
Blue Tabby/Tan
Gold/Brown
Chocolate/Red
Blue Tick/Brown
Tan/Red
Apricot/Tricolor
White/Seal Point
Brown Brindle/Brown Merle
Green/Orange
Calico/Calico
Red Tick/Brown
Orange Tabby/Tortie Point
Fawn/Tricolor
Orange Tabby/Orange Tabby
White/Tortie
White/Flame Point
Tricolor/Chocolate
Buff/Yellow
White/Gray Tiger
Black/Seal Point
Cream/Yellow
Brown/Black Tabby
Liver/Chocolate
Agouti/White
Blue Smoke/White
Flame Point/White
Orange Tabby/Apricot
Silver/Gray
Blue Merle/Red Merle
Black/Yellow Brindle
Brown/Pink
Green/White
Blue Merle/Cream
Yellow Brindle/Blue
White/Blue Cream
Orange Tabby/Brown
Seal Point/Gray
Brown Tabby/Orange Tabby
Tan/Brown Brindle
Torbie/Blue Cream
Red/Red Tick
Gold/Yellow
Black Tabby/Black
Brown/Orange
White/Calico Point
Ruddy/Cream
Liver/Buff
Black/Green
Brown Tabby/Black Brindle
Brown/Brown Tabby
Red/Green
Lynx Point/Tortie Point
Sable/Buff
Brown Brindle/Blue Tick
Red/Yellow
Black Smoke/Black
Black/Black Tabby
Blue/Gray
Silver Tabby/Black
Chocolate/Red Tick
Green/Gray
Agouti/Brown Tabby
Yellow/Brown
Black Smoke/Brown Tabby
Cream/Silver
Tricolor/Tan
Buff/Cream
Silver/Cream
Lynx Point/Gray Tabby
Gray/Cream
Black Smoke/Blue Tick
Black/Silver Tabby
Red/Tricolor
Brown/Brown Merle
Black Smoke/Gray
Tricolor/Orange
Tan/Blue
Black/Brown Merle
White/Liver Tick
Torbie/Brown
Tricolor/Brown Brindle
Cream/Red Tick
Brown/Red Merle
Black Brindle/Brown Brindle
Blue/Calico
Black Tiger/White
Tan/Yellow Brindle
Blue Cream/Tortie
Tortie/Brown
Tortie/Blue Tabby
Black Tabby/Orange
Blue/Cream
Tricolor/Silver
Tan/Gold
Tortie/Black Smoke
Brown Merle/Tan
Calico/Blue Tabby
Orange Tabby/Black
Gold/Cream
Blue Tabby/Black
Blue Merle/Brown Brindle
Brown/Black Brindle
White/Brown Tiger
Lilac Point/Cream
Tan/Red Tick
Tricolor/Blue Tick
White/Pink
Black Brindle/Black

In [61]:
colorNew=[]
for i in df.Color_intake:
    if "/" in i:
        i="Bicolor"
    elif "Tabby" in i:
        i='Tabby'
    elif "Brindle" in i:
        i="Tabby"
    elif "Merle" in i:
        i="Merle"
    elif "Tiger" in i:
        i="Tiger"
    elif "Tortie" in i:
        i="Tabby"
    elif "Calico" in i:
        i="Tabby"
    elif "Torbie" in i:
        i="Tabby"
    elif i=="Apricot" or i=="Gold" or i=="Yellow" or i=="Fawn":
        i="Orange"
    elif "Blue" in i:
        i="Blue"
    elif "Black" in i or i=="Sable":
        i="Black"
    elif i=="Liver":
        i="Brown"
    elif "Point" in i:
        i='Point'
    elif "Tick" in i:
        i="Point"
    else:
        i=i
    colorNew.append(i)
print(set(colorNew))
print(len(set(colorNew)))

{'Bicolor', 'Merle', 'Blue', 'Green', 'Orange', 'Brown', 'Tabby', 'Red', 'Point', 'Agouti', 'Tan', 'Buff', 'Tricolor', 'White', 'Chocolate', 'Silver', 'Pink', 'Gray', 'Cream', 'Black', 'Tiger'}
21

In [62]:
df['Color_intake']=colorNew

In [63]:
color_counts=df['Color_intake'].value_counts()
color_counts

Bicolor      16235
Tabby         6851
Black         3273
Brown         1875
White         1017
Blue           775
Tan            652
Point          640
Tricolor       636
Red            411
Orange         355
Gray           253
Cream          158
Buff           149
Chocolate      143
Merle          117
Pink            21
Silver          15
Tiger           12
Green           11
Agouti           7
Name: Color_intake, dtype: int64

In [64]:
replace_color=color_counts.loc[color_counts<500].index.tolist()
for i in replace_color:
    df.Color_intake = df.Color_intake.replace(i,"Other")

df.Color_intake.value_counts()

Bicolor     16235
Tabby        6851
Black        3273
Brown        1875
Other        1652
White        1017
Blue          775
Tan           652
Point         640
Tricolor      636
Name: Color_intake, dtype: int64

In [65]:
df.head()

,Animal ID,Name_intake,DateTime_intake,Found_Location,Intake_Type,IntakeCondition,Animal_Type_intake,Sex_Intake,Color_intake,DateTime_outcome,Outcome_Type,Sex_upon_Outcome,fixed_changed,Age_Bucket,DateTime_length,Breed_Type
0,A730601,No,2016-07-07 12:11:00,1109 Shady Ln in Austin (TX),Stray,Normal,Cat,Intact Male,Tabby,2016-07-08 09:00:00,Transfer,Neutered Male,1,7-12 months,0 days 20:49:00,Mix
2,A676515,Yes,2014-04-11 08:45:00,615 E. Wonsley in Austin (TX),Stray,Normal,Dog,Intact Male,Bicolor,2014-04-14 18:38:00,Return to Owner,Neutered Male,1,1-6 months,3 days 09:53:00,Mix
4,A679549,Yes,2014-05-22 15:43:00,124 W Anderson in Austin (TX),Stray,Normal,Cat,Intact Male,Bicolor,2014-06-16 13:54:00,Transfer,Neutered Male,1,1-6 months,24 days 22:11:00,Mix
5,A683798,Yes,2016-07-21 12:16:00,3118 Windsor Rd in Austin (TX),Stray,Normal,Cat,Spayed Female,Bicolor,2016-10-18 10:55:00,Adoption,Spayed Female,0,1-3 years,88 days 22:39:00,Mix
9,A683656,No,2014-07-13 13:20:00,8238 Research Blvd in Austin (TX),Stray,Normal,Cat,Intact Male,Point,2014-07-17 16:57:00,Adoption,Neutered Male,1,1-6 months,4 days 03:37:00,Mix

# Divide to two dataframes (intake and outcome)

In [66]:
intake_df=df[['Animal ID','DateTime_intake','Found_Location','Intake_Type','IntakeCondition',
             'Animal_Type_intake',
              'Name_intake',
             'Sex_Intake',
             'Color_intake',
             'Breed_Type']]

columns_intake=['animal_id','datetime_intake','found_location','intake_type','intake_condition','animal_type_intake',
        'name_intake','sex_intake','color_intake','breed_type']

intake_df.columns =columns_intake
intake_df.head()

,animal_id,datetime_intake,found_location,intake_type,intake_condition,animal_type_intake,name_intake,sex_intake,color_intake,breed_type
0,A730601,2016-07-07 12:11:00,1109 Shady Ln in Austin (TX),Stray,Normal,Cat,No,Intact Male,Tabby,Mix
2,A676515,2014-04-11 08:45:00,615 E. Wonsley in Austin (TX),Stray,Normal,Dog,Yes,Intact Male,Bicolor,Mix
4,A679549,2014-05-22 15:43:00,124 W Anderson in Austin (TX),Stray,Normal,Cat,Yes,Intact Male,Bicolor,Mix
5,A683798,2016-07-21 12:16:00,3118 Windsor Rd in Austin (TX),Stray,Normal,Cat,Yes,Spayed Female,Bicolor,Mix
9,A683656,2014-07-13 13:20:00,8238 Research Blvd in Austin (TX),Stray,Normal,Cat,No,Intact Male,Point,Mix

In [67]:
intake_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 33606 entries, 0 to 76975
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   animal_id           33606 non-null  object
 1   datetime_intake     33606 non-null  datetime64[ns]
 2   found_location      33606 non-null  object
 3   intake_type         33606 non-null  object
 4   intake_condition    33606 non-null  object
 5   animal_type_intake  33606 non-null  object
 6   name_intake         33606 non-null  object
 7   sex_intake          33606 non-null  object
 8   color_intake        33606 non-null  object
 9   breed_type          33606 non-null  object
dtypes: datetime64[ns](1), object(9)
memory usage: 2.8+ MB

In [68]:
outcome_df=df[['Animal ID','DateTime_outcome',
              'Outcome_Type',
              'Sex_upon_Outcome','fixed_changed','Age_Bucket','DateTime_length']]

columns_outcome=['animal_id','datetime_outcome','outcome_type',
                 'sex_upon_outcome','fixed_changed','age_bucket','datetime_length']

outcome_df.columns=columns_outcome

outcome_df.head()

,animal_id,datetime_outcome,outcome_type,sex_upon_outcome,fixed_changed,age_bucket,datetime_length
0,A730601,2016-07-08 09:00:00,Transfer,Neutered Male,1,7-12 months,0 days 20:49:00
2,A676515,2014-04-14 18:38:00,Return to Owner,Neutered Male,1,1-6 months,3 days 09:53:00
4,A679549,2014-06-16 13:54:00,Transfer,Neutered Male,1,1-6 months,24 days 22:11:00
5,A683798,2016-10-18 10:55:00,Adoption,Spayed Female,0,1-3 years,88 days 22:39:00
9,A683656,2014-07-17 16:57:00,Adoption,Neutered Male,1,1-6 months,4 days 03:37:00

In [69]:
outcome_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 33606 entries, 0 to 76975
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   animal_id         33606 non-null  object
 1   datetime_outcome  33606 non-null  datetime64[ns]
 2   outcome_type      33606 non-null  object
 3   sex_upon_outcome  33606 non-null  object
 4   fixed_changed     33606 non-null  int64
 5   age_bucket        33606 non-null  object
 6   datetime_length   33606 non-null  timedelta64[ns]
dtypes: datetime64[ns](1), int64(1), object(4), timedelta64[ns](1)
memory usage: 2.1+ MB

# Connect to SQL

In [70]:
db_string = f"postgres://postgres:{db_password}@127.0.0.1:5432/project_animal"

In [71]:
engine = create_engine(db_string)

In [72]:
# Save intake_df to database
intake_df.to_sql(name='animal_intake', con=engine,index=False, if_exists='replace')

In [73]:
# Save outcome_df to database
outcome_df.to_sql(name='animal_outcome', con=engine,index=False, if_exists='replace')

/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages/pandas/core/generic.py:2615: UserWarning: the 'timedelta' type is not supported, and will be written as integer values (ns frequency) to the database.
  method=method,

# Import table from SQL to Pandas

In [75]:
# reading a SQL query using pandas
sql_query = pd.read_sql_query("SELECT * FROM result", engine)
# saving SQL table in a pandas data frame
result_df = pd.DataFrame(sql_query)
# printing the dataframe
result_df.head()

,animal_id,datetime_intake,found_location,intake_type,intake_condition,animal_type_intake,name_intake,sex_intake,color_intake,breed_type,datetime_outcome,outcome_type,sex_upon_outcome,fixed_changed,age_bucket,datetime_length
0,A730601,2016-07-07 12:11:00,1109 Shady Ln in Austin (TX),Stray,Normal,Cat,No,Intact Male,Tabby,Mix,2016-07-08 09:00:00,Transfer,Neutered Male,1,7-12 months,74940000000000
1,A676515,2014-04-11 08:45:00,615 E. Wonsley in Austin (TX),Stray,Normal,Dog,Yes,Intact Male,Bicolor,Mix,2014-04-14 18:38:00,Return to Owner,Neutered Male,1,1-6 months,294780000000000
2,A679549,2014-05-22 15:43:00,124 W Anderson in Austin (TX),Stray,Normal,Cat,Yes,Intact Male,Bicolor,Mix,2014-06-16 13:54:00,Transfer,Neutered Male,1,1-6 months,2153460000000000
3,A683798,2016-07-21 12:16:00,3118 Windsor Rd in Austin (TX),Stray,Normal,Cat,Yes,Spayed Female,Bicolor,Mix,2016-10-18 10:55:00,Adoption,Spayed Female,0,1-3 years,7684740000000000
4,A683656,2014-07-13 13:20:00,8238 Research Blvd in Austin (TX),Stray,Normal,Cat,No,Intact Male,Point,Mix,2014-07-17 16:57:00,Adoption,Neutered Male,1,1-6 months,358620000000000

In [76]:
result_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33606 entries, 0 to 33605
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   animal_id           33606 non-null  object
 1   datetime_intake     33606 non-null  datetime64[ns]
 2   found_location      33606 non-null  object
 3   intake_type         33606 non-null  object
 4   intake_condition    33606 non-null  object
 5   animal_type_intake  33606 non-null  object
 6   name_intake         33606 non-null  object
 7   sex_intake          33606 non-null  object
 8   color_intake        33606 non-null  object
 9   breed_type          33606 non-null  object
 10  datetime_outcome    33606 non-null  datetime64[ns]
 11  outcome_type        33606 non-null  object
 12  sex_upon_outcome    33606 non-null  object
 13  fixed_changed       33606 non-null  int64
 14  age_bucket          33606 non-null  object
 15  datetime_length     33606 non-null  int64
dtypes: datetime64[ns](2), int64(2), object(12)
memory usage: 4.1+ MB

In [77]:
result_df.to_csv('result.csv', index=False)